### ISSUE TITLE
Move isParamPan/isParamPitch/isParamQuantizedStutter/isParamStutter out of View Class

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#1008]
### Please describe the problem:

These functions should not be part of the view class.

### What is the expected behavior?

They should belong to another more appropriate class as freestanding functions. E.g. param class?

Also add documentation as to how the functions work.

E.g. IsParamStutter requires UNPATCHED_SOUND and UNPATCHED_GLOBAL as the paramKind because UNPATCHED_GLOBAL is returned as the ParamKind in the context of Song/Arranger/Audio Clip/Kit Affect Entire and UNPATCHED_SOUND is returned as the ParamKind in the context of Synths/Kit Rows.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment]
I think the most appropriate spot would be to make them free standing functions in the param namespace

**Comment by sapphire-arches** [comment]
This was done as part of #1011, specifically https://github.com/SynthstromAudible/DelugeFirmware/pull/1011/commits/b193a731de9c977e8a70eeb6edece20310052b94
