### ISSUE TITLE
Keyboard in file browser not showing when scrolling with horizontal encode

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#1030]
### Please describe the problem:

When in the file browser you scroll with the horizontal encoder, the name bar is shifting. When you then type with the pads, it types but the keyboard is not present.

### What is the expected behavior?

The keyboard should come up.

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.1.0-DEV-85997821

**Comment by sichtbeton** [comment]
https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/86356844-1216-4b66-98ae-61225223429e

**Comment by sapphire-arches** [comment]
This bug is actually quite old, potentially even going back to the initial OSS release.

**Comment by sichtbeton** [comment]
> This bug is actually quite old, potentially even going back to the initial OSS release.

And obviously didnt bother anyone since :-)
