### ISSUE TITLE
Mod matrix flashing incorrect pads

### ISSUE THREAD

**Issue by entzmingerc** [SynthstromAudible/DelugeFirmware#1037]
### Please describe the problem:

Some of the patches reported in the mod matrix in the Sound Menu are displayed incorrectly. Some flashing pads that display the connections are also incorrect. When not inside the mod matrix menu at all, when using the shortcut to view ARP RATE value, it will show ENV1 flashing even though that connection isn't possible.

### What is the expected behavior?

I was testing the synth presets "pitch1, pitch2, pitch3, and pitch4" on firmware c1.0.0. The presets are available on github [from this repo](https://github.com/entzmingerc/DelugeSynthPresets/tree/main/SYNTHS/Artists/postsolarpunk/synths)

### preset name: pitch1
ENV2 50 ARP RATE, but LPF FREQ is flashing, should be ENV2 50.0 FOLD
LFO1 20 ARP RATE, but LPF FREQ is flahsing, should be LFO1 20.0 FOLD
ENV2 -5 ENV2 ATTACK is correct, but OSC1 TRANSPOSE is flashing instead of ENV2 ATTACK
	
### preset name: pitch2
LFO1 LFO1 8.00 ARP RATE, but TRANSPOSE is flashing, should be ARP RATE flashing
ARP RATE is patched to LFO1, but ENV1 is also flashing, ENV1 should not be flashing
LFO1 12.0 LFO2 RATE, but LFO1 RATE is flashing, should be LFO2 RATE
LFO2 3.00 LFO2 RATE, but LFO1 RATE is flashing, should be LFO2 RATE
LFO1 -17. OSC2 PITCH, but LFO1 RATE is flashing, should be OSC2 PITCH, should display -17.7, seems specific to negative numbers
ENV1 19 ARP RATE, but PW is flashing, should be PW

### preset name: pitch3
LFO2 -11. OSC1 PITCH, should display -11.3 for LFO2 to OSC1 PITCH, seems specific to negative numbers
LFO2 10.0 ARP RATE, but OSC1 TRANSPOSE is flashing, should be LFO2 10.0 FOLD
LFO1 15.0 ARP RATE, but MASTER LEVEL is flashing, should be LFO1 15.0 FOLD

### preset name: pitch4
LFO1 15.0 ARP RATE, patch exists but OSC1 TRANSPOSE is flashing instead of ARP RATE
LFO1 15.0 ARP RATE, patch exists but OSC1 TRANSPOSE is flashing instead of FOLD, should be LFO1 15.0 FOLD
LFO2 10.0 ARP RATE, but OSC1 TRANSPOSE is flashing, should be LFO2 10.0 FOLD

Oh if I scroll left instead of right through the menu I get the following
LFO1 15.0 ARP RATE, patch exists but DELAY TIME is flashing instead of ARP RATE
LFO1 15.0 ARP RATE, patch exists but DELAY TIME is flashing instead of FOLD, should be LFO1 15.0 FOLD
LFO2 10.0 ARP RATE, but DELAY TIME is flashing, should be LFO2 10.0 FOLD

looks like it's keeping the latest successful destination

scrolling right
LFO1 13.6 OSC1 PITCH - good
LFO1 15.0 ARP RATE - bad, OSC1 PITCH still flashing
LFO2 10.0 ARP RATE - bad
LFO1 15.0 ARP RATE - bad
LFO1 17.7 DELAY RATE - good

scrolling left
LFO1 17.7 DELAY RATE - good
LFO1 15.0 ARP RATE - bad, DELAY RATE still flashing
LFO2 10.0 ARP RATE - bad
LFO1 15.0 ARP RATE - bad
LFO1 13.6 OSC1 PITCH - good
	

### Is there a relevant Pull request?

https://github.com/SynthstromAudible/DelugeFirmware/pull/157

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.0/Amadeus

### What is the firmware name:

deluge-c1_0_0.bin

### If possible provide the steps to reproduce the issue and upload additional media:

information above! :)
really cool feature btw <3

**Comment by sapphire-arches** [comment]
We suspect this might require something similar to #723
