### ISSUE TITLE
Nudging two or more notes of the same row at the same time on pad grid can create inconsistencies.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#1048]
### Please describe the problem:

1) Enter two notes on the same row of a synth clip
2) Press and hold each note's pad (start from right to left to avoid note length extending.
3) Press and turn <> encoder to nudge clips, turn 3 times counter clockwise then 2 times clockwise
4) Press one pad and press <> encoder to check current nudge amount
5) Now press the other pad and press <> encoder to check current nudge amount
6) Note that one pad has a nudge of -2 and the other -3.

### What is the expected behavior?

Nudge amounts should be the same when editing at the same time. 

~~For note probability, one note will have latching on, not sure if that's default behavior or the same one knob off issue.~~

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.1.0 - 8FEA0F5

### If possible provide the steps to reproduce the issue and upload additional media:

This can also be observed by doing steps 1-3 but instead of turning 3 times, just turn counter clockwise and then clockwise back and forth, eventually one of the notes will start nudging farther and farther away while the other remains in the same place

**Comment by m-m-adams** [comment]
The latching is intended behaviour, if you're holding multiple notes in a row the probability system interprets it as desiring them all to play/not play together
