### ISSUE TITLE
Highlighted areas in Audio Source and in Multisample Note Ranges extend further than they should

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#1064]
### Please describe the problem:

Lumping together because these seem very small and are somewhat related. Both are OLED only.

**Audio Source:**
When entering the Audio Source menu for an Audio Clip (LEARN/INPUT + PAD ROW in SONG view), if you scroll down to an option with "(Monitoring)" at the end, when the text scrolls to reveal the full text, an extra highlighted section clips past the bounds of the selection. (Picture example [1] below)

**Multisample Note Range Start/End selection:**
When editing Note Range points in a multisample (SHIFT+BROWSE when multisample preset is selected [eg. 170-Sitar]), when you turn the horizontal encoder to switch from selecting a whole Note Range to a Note Range's Start or End point, an extra 1px of vertical highlighted section is added, which I think is undesirable and unintentional. (Picture example [2] below)

### What is the expected behavior?

**Audio Source:**
No highlighted section should clip through the selection's bounds

**Multisample Note Range Start/End selection:**
The height of the highlighted section shouldn't change when switching, just the horizontal portion.
Maintaining a gap between lists is present throughout the OLED UI.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.1.0 - 1AD7933 (1/24)

### If possible provide the steps to reproduce the issue and upload additional media:

[1 - Audio Source]
![deluge_monitoring_highlight_clipping](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/1b26d03d-f827-45f5-a635-9d0113ad362c)

[2 - Multisample Note Range Start/End selection]
![deluge_multisample_gap_highlight](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/8dbc8761-97f5-40c3-8539-533d7d5e6d5c)

**Comment by seangoodvibes** [comment]
Fixed the audio source one.

Still have to do the multi sample one.
