### ISSUE TITLE
Feature - Can we make clips scroll with playback like in arranger?

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#1086]
### Please describe the problem:

In arranger the cross screen button enables automatic scrolling of the grid so you can always see what step in the sequence is being auditioned.

In clip's, cross screen doesn't do that, rather it enables cross screen editing

### What is the expected behavior?

Can we enable an alternate cross-screen button behaviour?

e.g. Press cross-screen to enable cross-screen editing
Press shift-cross screen to enable automatic scrolling (the cross-screen button blinks)

or vice versa?

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by sapphire-arches** [comment]
We probably should scroll increments of the current zoom level rather than per-square like arranger does, to keep cross-screen (and probably other UI subsystems) happy.
