### ISSUE TITLE
Change in Flash Storage Offsets has messed up Default Settings

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#1152]
### Please describe the problem:

Due to the change in flash storage offsets, users are noticing default settings that they did not personally set.

### What is the expected behavior?

Let's reset the flash storage to default on initial Beethoven 1.1.0 firmware load so that users have the right default settings.

We can add a note "Sorry we messed up flash offsets at the first community release, we patched in 1.1 but the only way to fix this is resetting them for everyone"

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Built from community

**Comment by m-m-adams** [comment]
With the factory reset fixed I think it's better to give users the option, we can just mention it in the release notes
