### ISSUE TITLE
Misc bugs with sidebar functions in keyboard mode

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#1231]
### Please describe the problem:

MODWHEEL:
- Modweel default values for each pad should go **from 0** to 127 equally spaced, instead of **from 15** to 127 (for velocity it is fine to go from 15 to 127)

SCALES:
- If have  a 7-note scale selected and put notes in the clip in all the notes from the scale, and then in keyboard mode you hold a scale pad and turn the up/down know it will let you scroll through less-than-7 scales totally screwing your clip, with notes that are now hidden and can't be removed. It should only let you scroll through scales compatible with your existing clip notes
- If a pentatonic scale was already set in one of the pads, and you change to another pad which is Major, input notes in the clip, then try to press the Pentatonic scale pad, it will screw your clip. It should say "CAN'T" in the screen or something like that

MODWHEEL and VELOCITY:
- I still think that these two bars should have a special treatment in regards to long press vs short press. They should only work with short press to allow you to slide your finger and always let the pad selected of the last thing you touched and not jump back.

GENERAL:
- Holding the top pad and turning the Select knob changes the mode of the sidebar but at the same time changes the synth preset. It should not change the sidebar mode, as it leads to confusion. Only the <> knob should change the sidebar modes

### What is the expected behavior?

.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by robmccoll** [comment]
The select knob fix is in #1237. With respect to scales, I thought the clip view used to show out-of-key notes when they are present? Is that a bug of it's own? Are we trying to shift notes into scale or something?
