### ISSUE TITLE
Voice drops that don’t occur on official

### ISSUE THREAD

**Issue by Icoustic** [SynthstromAudible/DelugeFirmware#1264]
### Please describe the problem:

Here’s another of my projects made on official that have a lot of voice drops even on one of the latest nightly builds, feb 19. All the active tracks in arranger play normally on official firmware.
(The one I mentioned previously, @m-m-adams )

Collect-zip: https://we.tl/t-0yPHzgDbVi

### What is the expected behavior?

No voice drops, at least very minimal 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### If possible provide the steps to reproduce the issue and upload additional media:

Play the song, and voices drop, such as the respirator sample, synth pad etc.

**Comment by m-m-adams** [comment]
Great, thanks for sharing! This actually culls a lot of voices in both official and community - on the whole community is culling less, but the times/voices it chooses to cull are much worse. I'm going to stew a bit on how to fix this!

**Comment by m-m-adams** [comment]
Any chance you have a stereo version of this song? It's a bit uncomfortable to listen to in headphones and I'll be hearing it on repeat this week

**Comment by Icoustic** [comment]
> Any chance you have a stereo version of this song? It's a bit uncomfortable to listen to in headphones and I'll be hearing it on repeat this week

Noo I work in dual mono send/ return setup, sorry. You can pan stuff back to center if you must 😖
