### ISSUE TITLE
Strange noise that shifts in tone while paused

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#1289]
### Please describe the problem:

**UPDATE:** it seems to be connected to the mutable reverb. changing the reverb model back to Freeverb gets rid of the noise.

After playing this song for a couple of bars and then stopping playback, wait for ca 10 seconds, then a strange noise can be heard while the Deluge is idle. the color of the noise even changes when hitting playback (you hear it when no clip is playing but the deluge itself plays). this noise doesnt go away, only reloading the song works.

https://drive.google.com/file/d/10M8WfIiOpqsLMnfVa5rqiyojEh0Uuu5S/view?usp=sharing

### What is the expected behavior?

no noise

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

Deluge Beta Release 20240221

### If possible provide the steps to reproduce the issue and upload additional media:

load song
play for 4 bars
stop playback
listen for noise

**Comment by sapphire-arches** [comment]
I've attached a minimized version of the song with only the problematic kit row. Must play for ~4 bars before enough energy is in the problematic frequency for it to go in to self-oscillation.

- Seems to be related to the render window size, the pitch of the oscillation changes when UI work happens.
- You need a pretty high volume to actually hear the noise. My headphones are unlistenably loud at ~1/4 gold knob but the noise is only audible in detail at like 1/2 gold knob.
- There's some timeout where it suddenly jumps to self-oscillation -- the volume decreases over time and then starts crackling/breaking up and then jumps in to white noise + self oscillation. Maybe the reverb tanks aren't getting emptied when the rendering shutoff detects low output level, and something about that process is causing some bad data to get inserted into the tanks?

[NoiseReduced.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/14366417/NoiseReduced.zip)
