### ISSUE TITLE
Massive Voice stealing in drum kits with Beta firmware.

### ISSUE THREAD

**Issue by highsiderr** [SynthstromAudible/DelugeFirmware#1296]
### Please describe the problem:

Massive Voice stealing with new Beta Version

### What is the expected behavior?

If I load the track with the 1.0.1 firmware, no voices are stolen. 
With the new beta, voices are stolen in the drum kit.
[songs final.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/14373013/songs.final.zip)

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

other

### What is the firmware name:

deluge-c1_1_0

**Comment by m-m-adams** [comment]
Confirmed - on last release this is hard culling occasionally, on current beta it's soft culling frequently. 

I'm going to look at tweaking the cull thresholds - with the changes to the cull system I think we can push them a bit higher now

Thanks for sharing the song! It's a fun listen

**Comment by highsiderr** [comment]
THX @m-m-adams
