### ISSUE TITLE
Potential bug with DrumKeyboardScreen note retriggering

### ISSUE THREAD

**Issue by trappar** [SynthstromAudible/DelugeFirmware#131]
When in the DrumKeyboardScreen (from https://github.com/SynthstromAudible/DelugeFirmware/pull/112), I've found that if you hold a pad for one sample and then press a different pad for the same sample but at a different velocity, it does not retrigger the sample at the new velocity. This seems counter-intuitive to me and would make it more difficult to play in complex parts with ghost notes as it's quite easy to accidentally hold a pad a little too long and swallow a note.

**Comment by weavermedia** [comment]
Duplicate of this https://github.com/SynthstromAudible/DelugeFirmware/issues/126

**Comment by trappar** [comment]
Yep, sorry didn't spot it.
