### ISSUE TITLE
Delete automation when sticky shift is on.

### ISSUE THREAD

**Issue by x3003** [SynthstromAudible/DelugeFirmware#1311]
### Please describe the problem:

The sticky shift is a nice feature. Sometimes however when you are trying out some stuff fast, you might delete the automation because you forgot sticky shift was on. ¯\_(ツ)_/¯

### What is the expected behavior?

As an enhancement:  Just using shift + press gold knob(s) to delete automation, like the way it was before.
I now turned this feature off, as I deleted the automation a few times too many....

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly, other

### What is the firmware name:

c1.1.0

**Comment by m-m-adams** [comment]
We're not going to change this - sticky shift intentionally behaves exactly like shift to avoid confusion and allow one handed operation. You can undo automation deletion if you do it by mistake
