### ISSUE TITLE
Freeze (crash) selecting Filters via Sound Menu

### ISSUE THREAD

**Issue by MichaelinVic** [SynthstromAudible/DelugeFirmware#1355]
### Please describe the problem:

Freeze selecting Filters via Sound Menu. Seems to happen only for some songs. I have attached an offending one.

### What is the expected behavior?

Selecting Filters via the Song Menu shows filter options for clip.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

c1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

1. Load  song
2. Select synth clip
3. spSelect
4. tSelect to Filters
5. spSelect

[SONG2026..xml.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/14411978/SONG2026.xml.zip)

**Comment by sapphire-arches** [comment]
This occurs specifically with FM filters.

**Comment by m-m-adams** [comment]
It's an infinite loop since none of the filter items are relevant. We need to add an isRelevant to the filter item itself
