### ISSUE TITLE
Arpeggiator on MIDI tracks is ratcheting randomly by default

### ISSUE THREAD

**Issue by staminajim** [SynthstromAudible/DelugeFirmware#1368]
### Please describe the problem:

Hello! I installed the nightly build today and found that the Arpeggiator is ratcheting randomly by default (I haven't turned any ratchet setting on) if the track is assigned to a midi channel.

It doesn't ratchet randomly when assigning the track to an internal synth.

Have tried it on old songs, new songs, and various hardware synths + midi channels with the same result.

Does not reproduce on c1.0.1 - I suspect it's related to the new Arp changes that just went it.

### What is the expected behavior?

The Arpeggiator shouldn't randomly ratchet unless you tell it to (haven't actually found out how you're supposed to do that yet)

### Is there a relevant Pull request?

N/A

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_02_28-c8a631f

### If possible provide the steps to reproduce the issue and upload additional media:

1. Start a new song
2. Add a new Clip and assign to MIDI channel connected to hardware synth
3. Lay down 3 notes to cover the bar
4. Turn on the Arp
5. Listen to random ratchet notes on hardware synth.

**Comment by seangoodvibes** [comment]
@soymonitus

**Comment by m-m-adams** [comment]
It's one of the settings in the arpeggiator - click select, then the arp menu lets you choose ratchet amounts and probability

That said we should probably have it off by default and matching in both synth and midi arps

**Comment by soymonitus** [comment]
@staminajim  If your default synth patch that is selected when you create a new clip has arpeggiator settings in place, when you convert the Synth clip to Midi clip, it will inherit the arpeggiator settings from the synth patch. May this be the case? because it happened to me and I thought I had screwed my implementation and then found out it was due to this reason.

**Comment by staminajim** [comment]
@soymonitus I get this behaviour going from the factory 001 bass preset (no arp) -> MIDI (tested with channels 1-> 3).

This was also on a fresh update and I haven't touched any ratchet settings at all - only turning ARP mode to one of the Up or Down settings.

**Comment by staminajim** [comment]
Wondering if the problem is in here:

https://github.com/SynthstromAudible/DelugeFirmware/blob/852d1b49ba2a544564534380bdb5153cb14d9202/src/deluge/gui/menu_item/arpeggiator/midi_cv/ratchet_amount.h#L27-L34

This only gets called if `output->type == OutputType::MIDI_OUT || output->type == OutputType::CV` (otherwise `ratchet_amount` = 0) and plugging in some numbers looks like it might be setting ratchet_amount to a non-zero value?

`readCurrentValue()` gets called with `arpeggiatorRatchetAmount` = 0
which calls `setValue(25)`

`writeCurrentValue()` gets called and `arpeggiatorRatchetAmount` is set to -23?

**Comment by soymonitus** [comment]
> Wondering if the problem is in here:
> 
> 
> 
> https://github.com/SynthstromAudible/DelugeFirmware/blob/852d1b49ba2a544564534380bdb5153cb14d9202/src/deluge/gui/menu_item/arpeggiator/midi_cv/ratchet_amount.h#L27-L34
> 
> 
> 
> This only gets called if `output->type == OutputType::MIDI_OUT || output->type == OutputType::CV` (otherwise `ratchet_amount` = 0) and plugging in some numbers looks like it might be setting ratchet_amount to a non-zero value?
> 
> 
> 
> `readCurrentValue()` gets called with `arpeggiatorRatchetAmount` = 0
> 
> which calls `setValue(25)`
> 
> 
> 
> `writeCurrentValue()` gets called and `arpeggiatorRatchetAmount` is set to -23?
> 
> 

I will take a look, thanks for testing!

**Comment by m-m-adams** [comment]
Fixed by #1378
