### ISSUE TITLE
Changing delay sync during playback causes unrecoverable crash/freeze 

### ISSUE THREAD

**Issue by malteohlers** [SynthstromAudible/DelugeFirmware#1406]
### Please describe the problem:

Changing delay sync from "2-bar-dtted" to "128th-tplts" during playback causes unrecoverable crash/freeze.

### What is the expected behavior?

Change delay sync to "128th-tplts" without crashing.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_03_02-24d68e3.bin

### If possible provide the steps to reproduce the issue and upload additional media:

1. Turn Deluge on
2. Place a note on the pianoroll (eg. C3 in first position).
3. Set "Delay amount" => 1 (enabled)
4. Set "Delay sync" to "2-bar-dtted"
5. Press "Play"
6. Navigate to "Delay sync" with shortcut or menu
7. Turn Select knob to the left (towards 128th-tplts) = Crash!

**Comment by m-m-adams** [comment]
Not present on beta so probably buffer change related
