### ISSUE TITLE
Wavefolder modulation issues

### ISSUE THREAD

**Issue by pmeyerhiggins** [SynthstromAudible/DelugeFirmware#1416]
### Please describe the problem:

I have noticed a couple of problems relating to Wavefolder modulation (on OLED c1.0.1).
1. problem is to do with effect of modulation not matching expectations, and 2. is to do with how it appears in the Mod. Matrix.
1. 
If I raise the Wavefolder to 1 (to include it in the signal path) and connect ENV2 to it (at full level = 50), ENV2 does not have the expected affect on the wavefolder (raising the Wavefolder to full level following the ENV settings). It does have some effect (e.g. raise Wavefolder to 25, and the increase in harmonic content following the ENV can be heard).
BUT, if I raise the Wavefolder to 25 and connect LFO1 with intensity 20, the Wavefolder is modulated as expected

2. In the examples above, the Mod. Matrix reads:
"ENV2 50.0 ARP. RATE"
"LFO1 20.0 ARP. RATE" 

### What is the expected behavior?

I would expect the Modulations to affect the new parameters as they do typical Deluge parameters (i.e. Modulation level of 50 will sweep the parameter over the full range of its values from 0 - 50).
I would expect the Parameter to be modulated in the same way by envelopes and LFO.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.0/Amadeus

### What is the firmware name:

C1.0.1

### If possible provide the steps to reproduce the issue and upload additional media:

1. Turned on.
2. Initialised patch
3. Changed OSC 1 Type to SINE
4. Raised Wavefolder to "1" to include in signal path
5. Connected ENV2 -> Wavefolder with signal strength 50
6. Listen -> Wavefolder not modulated as expected.

**Comment by m-m-adams** [comment]
This is consistent with all other volume related deluge parameters. Modulation in deluge is multiplicative and the value you set is the middle value. In the example of setting fold to 1 the envelope modulates it to 2 at its maximum and zero at its minimum. I agree that this is unintuitive but changing it would break all backwards compatibility with old presets
