### ISSUE TITLE
Midi Notes lengths get truncated when recording in arranger mode

### ISSUE THREAD

**Issue by Radius9999** [SynthstromAudible/DelugeFirmware#1422]
### Please describe the problem:

When recording a midi track (to play an external synth) in arranger mode, long notes get truncated to almost 0 length intermittently.  Only occurs with quantization on.  When quantization is off, notes record properly.  (This does not happen when in song mode.)

### What is the expected behavior?

Note offs should not be quantized when quantization is enabled in arranger mode.  Note lengths should remain as played.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

C1.2.0

### If possible provide the steps to reproduce the issue and upload additional media:

https://github.com/SynthstromAudible/DelugeFirmware/assets/147354026/01157925-d96c-44e2-ae15-76efa1cf9b87

**Comment by m-m-adams** [comment]
What are your quantization settings?

**Comment by Radius9999** [comment]
It doesn't matter what the quantization settings are.  I've tried different settings.  But it's the note lengths we're talking about.  Those should not be quantized at all.

**Comment by m-m-adams** [comment]
Can you please share your quantization settings? The bug is clearly related to quantization, and I have not been able to reproduce it since limiting the quantization menu to the range of values actually supported by the deluge

**Comment by m-m-adams** [comment]
You can also try clearing your settings (hold select while booting) to see if that fixes the issue

**Comment by Radius9999** [comment]
I've already tried clearing settings.  By my quantization settings, you mean ....  I have it set to 16th notes under Settings-Recording-Quantization.  Is there some other place to adjust quantization?

**Comment by m-m-adams** [comment]
Nope that's it. I'll try 16th notes, I have mine at 64ths and haven't been noticing issues but possibly it's just close enough that I don't notice

**Comment by m-m-adams** [comment]
Ok yeah, reproduced
