### ISSUE TITLE
Deluge sending MIDI CC out (on cannel 1) when in Synth/Kit

### ISSUE THREAD

**Issue by patriciachadwick62** [SynthstromAudible/DelugeFirmware#1438]
### Please describe the problem:

- Deluge sending MIDI CC out when in Synth/Kit  turning gold Knobs

- also when then scrolling in the Browser

### What is the expected behavior?

- setting Synthparameters without sending MIDI CC out

- Browsing without sending MIDI

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_03_02-24d68e3  / deluge-v1_2_0-nightly+2024_03_05-bfc0fad

**Comment by soymonitus** [comment]
Take a look at midi settings -> midi follow and then channels and feedback channel. It will be ser to channel 1 for sure. Scroll them to unassigned
