### ISSUE TITLE
Turning master pitch >0 on a kit row set to "independent" pitch/speed results in sample not playing fully

### ISSUE THREAD

**Issue by nobodybelievesyou** [SynthstromAudible/DelugeFirmware#1444]
### Please describe the problem:

Turning master pitch above 0 on a kit row with pitch/speed set to "Independent" results in the sample playback being glitchy/truncated. Turning it back to 0 or below will cause it to play normally again.

Tested on Feb 21 community beta and the problem was not present in that build.

### What is the expected behavior?

Sound should playback fully/correctly at every pitch setting.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

Community beta March 5 2024

### If possible provide the steps to reproduce the issue and upload additional media:

- create a new kit
- load or record audio into a kit row
- set pitch/speed to "independent"
- set gold knob to custom 1
- turn knob until master pitch is greater than 0
- press audition pad or play notes entered into the kit row grid

https://github.com/SynthstromAudible/DelugeFirmware/assets/159941961/0021dfb2-290e-4fe7-8c5e-d9db1304adc1

**Comment by chee** [comment]
it was defos [this PR](https://github.com/SynthstromAudible/DelugeFirmware/commit/c8a631fdc67a7bdec915b931e1a2371910d8ea41) but i have no idea how. i've read it, and i do not understand how
