### ISSUE TITLE
Arpeggiator not working correctly in Kits

### ISSUE THREAD

**Issue by bnhrsch** [SynthstromAudible/DelugeFirmware#1558]
### Please describe the problem:

The arpeggiator doesn't change Octaves or Rhythms in Kits. Only the 'Random' octave mode seems to use octaves. 

### What is the expected behavior?

That the Arpeggiator follows the settings you set in octave and note mode. 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.2.0-Nightly-4437AF4

### If possible provide the steps to reproduce the issue and upload additional media:

Octaves:

- Create a kit
- Select a sample
- Turn the Arpeggiator on
- Increase the octaves to f.e. 4

Scroll through the Octave and Note modes. They do not use octaves (only random does)

Rhythms:

- Go into the Arpeggiator menu
- Scroll through the Rhythms
The rhythm doesn't change.

**Comment by soymonitus** [comment]
Please assign this to me. It stopped working after my refactor/cleanup of the arpeggiator code, but synths work, so should be an easy fix.
