### ISSUE TITLE
Example Module

### ISSUE THREAD

**Issue by hickscorp** [SynthstromAudible/DelugeFirmware#16]
Labels: Suggestion, Enhancements

Good morning,

This is amazing. This amazing. This is amazing.
I've been dreaming of making a specific plugin for my deluge for ages...

It'd be great to see a bit of documentation.
How to get started, where to look for, etc.
I would suggest a short architecture diagram of the code for a starter.

Then later, i would really like to know more about what is possible in terms of plugins - does the binary artifact have to be monolytic? Or can it accept additional components without having to recompile the entire thing?
I'm thinking distribution channels - would someone be able to get a plugin from a third party and flash it on the side, or would each plugin need to be flashed as part of the main firmware and therefore only one custom functionality could be added?

Lastly - are the binary artifacts required to be signed, is there any secure element onboard that would prevent someone to do certain things?

Thanks.
This is amazing. This is amazing. This is amazing.

**Comment by litui** [comment]
I love the enthusiasm!

As for documentation, much of it has been commented into the appropriate sections of the code by Rohan, but also there is https://docs.google.com/document/d/1alfwv48udgsfvpi7QQOHW2cWkQKUELlr5nNIhpyFxrI/edit as a starting point so far.

At present binary artifacts are monolithic builds. I have seen other projects implement plugins through mechanisms like dynamic ELF loading, but no such capability exists at present in the Deluge codebase, so a distribution would need to be a complete firmware image. I think there's a lot of room though for cut-down code in the form of demos.... it'd be interesting to see minimal implementations that exist to show what is possible, which could later be integrated as features, but that's my bias as an appreciator of the demoscene =)

To my knowledge, the security features of the RZ/A1LU chip have not been engaged in the past. I would be careful about engaging these features as there is presently no central signing authority for them and an end  developer could end up permanently locking themselves out of flashing their own hardware if they're not careful.
