### ISSUE TITLE
Harsh noise in the pan spread feature

### ISSUE THREAD

**Issue by synthpatches** [SynthstromAudible/DelugeFirmware#1626]
### Please describe the problem:

When you create a new patch, select ring as synth mode, add some noise and then select and increase the pan spread - there is a loud and harsh noise that can damage your ears.

### What is the expected behavior?

No harsh noise.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.0/Amadeus

### What is the firmware name:

C1.0.1

**Comment by m-m-adams** [comment]
Known bug in 1.0.1, it's fixed in the 1.1 beta

See the list of known issues here - https://github.com/SynthstromAudible/DelugeFirmware/releases/tag/release_1_0_1
