### ISSUE TITLE
Songs are not loading anymore since deluge-v1_2_0-nightly+2024_04_08-502dc21

### ISSUE THREAD

**Issue by busa-projects** [SynthstromAudible/DelugeFirmware#1695]
### Please describe the problem:

Since the deluge-v1_2_0-nightly+2024_04_08-502dc21, newer songs are not loaded anymore. Older songs dosn't seam to be affected. Latest working Build is deluge-v1_2_0-nightly+2024_04_07-c642a4d. If i try to load the song, i get a empty Son, like when i press "new Song". Also File Browser index is reseted. Next time i click load, the Index points to the First Song in Directory, and not to the one i loaded before.

### What is the expected behavior?

Loading of the Song

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_04_08-502dc21

### If possible provide the steps to reproduce the issue and upload additional media:

-Rename txt to XML and copy to SONG Folder
[SONG8.XML.txt](https://github.com/SynthstromAudible/DelugeFirmware/files/14922388/SONG8.XML.txt)
- Start Deluge
- Press load
- Browse to "Song8"
- Press load

**Comment by m-m-adams** [comment]
Should be fixed already, just hasn't been built into the nightly yet

**Comment by busa-projects** [comment]
confirmed. fixed with the latest nightly. thx
