### ISSUE TITLE
master clip volume does not hold

### ISSUE THREAD

**Issue by worker-gray** [SynthstromAudible/DelugeFirmware#1697]
RESOLVED- as if by magic

**Comment by sapphire-arches** [comment]
It would be helpful to have the song file that exhibits problematic behavior, since it seems like that clip is in a very particular state. Also, it would be good to try the 1.1 beta build to see if the problem has already been fixed.

**Comment by worker-gray** [comment]
I turned it off/on after trying to record a video and tried it again-- it worked.
