### ISSUE TITLE
Crash while loading songs

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#1730]
### Please describe the problem:

opening this song crashes the deluge with QR Code.

[SONG008 2.XML.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/14982842/SONG008.2.XML.zip)

![IMG_9267](https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/14c63442-cc1b-4944-b77b-efb7e6355af9)

### What is the expected behavior?

open the song as usual.

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_04_14-7d90449

### If possible provide the steps to reproduce the issue and upload additional media:

open the song.

**Comment by sapphire-arches** [comment]
E411 is "missing patched param".
```
arm-none-eabi-addr2line -Capife build/Release/deluge.elf 0x2011c6f5 0x2011c707 0x20100b65 0x200a7595 
```
This is probably due to the backup param manager stuff from #1658, I don't think I initialized the patched param manager.

**Comment by sichtbeton** [comment]
basically all songs saved prior to this nightly cant be opened. they simply crash. stumped.

**Comment by sapphire-arches** [comment]
This was indeed caused by #1658.

**Comment by sichtbeton** [comment]
Thanks for fixing this!
