### ISSUE TITLE
Fast CC changes from devices when Deluge is Host cause crashes

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1748]
### Please describe the problem:

See https://github.com/SynthstromAudible/DelugeFirmware/issues/1707#issuecomment-2064193436. Suspicion is that this is a USB host stack problem, which we probably can't fix for 1.1

### What is the expected behavior?

MIDI should not cause crashes.

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment]
I can't reproduce, I can get audio glitches if I really push the rate of CCs but not crashing
