### ISSUE TITLE
"File not found" when adding tracks to projects started on Official firmware

### ISSUE THREAD

**Issue by MkUltra85** [SynthstromAudible/DelugeFirmware#1792]
### Please describe the problem:

Some (but not all) projects that were started with the official firmware will not allow me to create new synth / kit / midi tracks after flashing to the new C1.1.0 firmware. When I press a new row in Song view (or when I press the row button in Arranger view), it gives me a "file not found" error. I can, however, still copy existing tracks. 

### What is the expected behavior?

Creating a new track.

### Is there a relevant Pull request?

I don't believe so

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

Community C1.1 Beethoven Beta

**Comment by m-m-adams** [comment]
Can you share an example? I've got ideas for a fix but don't have a way to test it

**Comment by m-m-adams** [comment]
As a temporary fix you can probably save and reload the song

**Comment by MkUltra85** [comment]
[MK - Jul 11 3.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/15142426/MK.-.Jul.11.3.zip)

Thanks for the quick response. Here's a project it happens with. I tried saving / reloading, but it didn't fix.

**Comment by m-m-adams** [comment]
Confirmed I can reproduce, I'll update when I have a fix
