### ISSUE TITLE
Text scrolling is too slow

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1793]
### Please describe the problem:

Text scrolling is noticeably slower/less smooth than previously.

### What is the expected behavior?

Scroll behavior should match pre task-handler.

### Is there a relevant Pull request?

#1708

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment]
Hm yeah - I wonder if the ui timer manager needs to be called more often

**Comment by sapphire-arches** [comment]
I think we might be calling USB stuff too infrequently as well, I get checksum errors trying to use sysex FW loading now.

**Comment by m-m-adams** [comment]
Ok, I think that one is in the playback handler task and probably shouldn't be
