### ISSUE TITLE
cannot create a new synth for a row in KIT view

### ISSUE THREAD

**Issue by nikodemus** [SynthstromAudible/DelugeFirmware#1806]
### Please describe the problem:

Creating a synth row in KIT view offers possibility of loading a synth, but not creating a new one.

### What is the expected behavior?

There should be a way to create a new synth.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

c1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

- Create new kit.
- Press AUDITION + SYNTH.
- Screen shows synths that could be loaded to the row.
- There doesn't appear to be any way to create a new synth instead of loading one.
- Pressing BACK loads the synth that was under the select cursor.

**Comment by m-m-adams** [comment]
Audition + load is now fixed, so that offers a way to make a default synth
