### ISSUE TITLE
SD cards with large numbers of presets can cause multi-second UI lag while scrolling presets.

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1871]
A user on discord reported that with their preset folder with several hundred presets caused noticable (>1 second) stalls during preset scrolling. Apparently official/4.1 can handle this situation, so we might have regressed it at some point.

Reported against 1.1 beta (744d1332dad16da37a50e721d3a0329059ba95a4)

**Comment by m-m-adams** [comment]
This doesn't happen on nightly as far as I can tell, so closing the issue
