### ISSUE TITLE
Default phase retrigger causes clicks when triggering note in FM Mode

### ISSUE THREAD

**Issue by requiets** [SynthstromAudible/DelugeFirmware#1946]
### Please describe the problem:

Triggering notes in audition or iso keyboard creates a pop/clipping/click noise at the beginning of the sample. This is most noticeable when playing medium or harder velocity and is not heard when lightly pressing or playing with playing with portamento. Prevalent in FM synth mode but have also experienced in other modes, though not often.

### What is the expected behavior?

Note triggers pitch without additional pop/click noise.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_05_16-f636f84

### If possible provide the steps to reproduce the issue and upload additional media:

Selected FM Synth Mode, press pad in either ISO keyboard or audition with medium or higher velocity.

**Comment by seangoodvibes** [comment]
DX7 FM synth or original FM synth?

**Comment by requiets** [comment]
FM Synth. My mistake - I thought that was the same as DX7 FM.

**Comment by sapphire-arches** [comment]
Is this different compared to prior firmware versions? if not, there's a few common causes: 
 - attack set to zero 
 - sample start not aligned to a zero crossing

**Comment by m-m-adams** [comment]
Yeah, the fix is to set phase retrigger to 0 on the carriers. It's 5th pad from the bottom in the oscillator column  

We should probably do that by default in FM synths instead of having it off

**Comment by m-m-adams** [comment]
Closing - clicks are already avoidable and they can be useful for sound design
