### ISSUE TITLE
Pan Parameter Value Display on OLED

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#195]
Discovered an issue with how the **Pan** parameter is being displayed on the OLED screen, both when changing the param using the select knob and the gold knob. See attached picture.

I am using the latest community build.

To replicate bug:

1) enter a clip
2) press shift + master pan
3) turn gold pan master fx knob or turn the select knob to change the parameter value

![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/138174805/e185aa96-bb7c-40f9-a55d-4e33baf29868)

![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/138174805/0570b85d-6c60-484a-8179-d4c3de42270e)

**Comment by m-m-adams** [comment]
Confirmed this is still happening

**Comment by m-m-adams** [comment]
The problem seems to be that pan.h is getting the limits from integer.h in menu_item instead of the integer.h in patched_param. This sets the limits to be 0-50, and there is int overflow when the value goes above 32
