### ISSUE TITLE
Automation overview doesn't display currently automated MIDI CC parameters

### ISSUE THREAD

**Issue by wargoth** [SynthstromAudible/DelugeFirmware#1956]
### Please describe the problem:

I recorded automation manually for a MIDI instrument. I would like to go to automation view to modify the parameter, however it's unavailable in the Automation overview screen. Only those parameters displayed which are listed in MIDIFollow.XML.

Simple solution would be to update MIDIFollow.XML with all available MIDI CCs. Or automation overview should list currently automated CC parameters dynamically. 

### What is the expected behavior?

MIDI CC parameters for which exists automation should be present on Automation overview screen.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.1.0-beta-4c130ec

### If possible provide the steps to reproduce the issue and upload additional media:

1.  Learn MIDI controller
2. Record automation manually by twisting knobs
3. Go to automation overview (SHIFT + CLIP)

**Comment by seangoodvibes** [comment]
You can still scroll to those other cc's that aren't on automation overview.

I understand your point tho.

That said, even with other clip types (eg synth) we've run into a point where we have more parameters than can be displayed on the grid. For example all the patch cables, the new automatable arp params.

So we can't use the automation overview to see automation for every single automatable param.

I'm really not sure what a good solution is if we want the automation overview to display an overview of every single param that's automatable ...
