### ISSUE TITLE
several occurences of clicks in the Deluge

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#1971]
### Please describe the problem:

There are several situations where the Deluge produces unwanted clicks that make a smooth product hard to achieve. it would be cool if there was a way to generally get rid of these. maybe there could be a global "crossfade value" that introduces a small fade (like in audioclips with "margins on"). this would lead to smoother results in the Deluge output.

The situations:

- audioclips looping (except when having recorded from external, then the margins feature prevents clicks by x-fade already)
- audioclips end (while there is an attack value for the first play of an audioclip, there is no release, so it clicks mostly) 
- sample loop points (a x-fade combined with a zero crossing detection would finally make the loop feature actually usable) 
- sudden value jumps (for example HPF or reverb amount, can be remedied by a small fade by hand but would be a QOL feature)
- stutter feature (the general clickiness can be avoided, "looking at Turnado...")

now if all these points would have a built in margin/ crossfade feature and the length of it could be changed (maybe globally for starters?) this would be very nice to have. all behind a community toggle.

### What is the expected behavior?

no clicks.

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

-

### If possible provide the steps to reproduce the issue and upload additional media:

try the click situations

**Comment by sapphire-arches** [comment]
I filed a couple bugs so we can track the components of this separately:
- Audio clip looping I think is covered by allowing fades and zero crossing detection.
- #1990 covers audio clip fadeout
- #1991 and #84 cover sample loop crossfade and zero crossing detection.
- #1989 covers modulation clicks. Stutter also falls under this I think

I'm going to close this issue in favor of the more specific ones, please open a separate bug if there's situations where we click that aren't covered by those more specific bugs.
