### ISSUE TITLE
Freezes when using Midi Loopback in certain situations

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#1993]
### Please describe the problem:

When you have a kit with midi rows (that send midi notes), and a sound kit row learned to that other row, then add some fill notes by holding SyncScaling and adding some notes to the grid, when you play the sequence and activate the fill mode, the first fill note plays fine, but the second note played will crash the deluge with a high volume buzz sound.
It also freezes just by pressing Record and having the playback reach any note in the midi row

### What is the expected behavior?

No crash

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

Beta

**Comment by soymonitus** [comment]
After some more digging I found another freeze, which is if you hit Record button, it also hangs.

But this is all related to Midi Loopback Enabled. If I disabled Midi Loopback none of this happens. So steps to reproduce:
- First, enable midi loopback
- Create a new kit and add a midi row, and a sound row
- learn the sound row to the midi row
- Now press play and do either of these:
- Add fill notes to the midi row
- Engage Record

With any of these two actions the Deluge hangs

**Comment by soymonitus** [comment]
@sapphire-arches

**Comment by m-m-adams** [comment]
Seems related to https://github.com/SynthstromAudible/DelugeFirmware/issues/1817

The playhead is continually being reset to the same position

**Comment by m-m-adams** [comment]
Fixed by removing loopback
