### ISSUE TITLE
Cluster pointers can get corrupted, somehow

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#1994]
### Please describe the problem:

We've had a few reports of clusters misbehaving
 - https://discord.com/channels/608916579421257728/608918533815926784/1242805835327995924 - During collect-all we get fragments of XML instead of the file contents (this is actually a 1.2 bug, see #1995)
 - https://discord.com/channels/608916579421257728/1138924035657449482/1242483870767779910 - Scrolling synth presets caused an assertion failure related to cluster fallout.

### What is the expected behavior?

No crash

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

other

### What is the firmware name:

1.1.0-beta-d2e6588

**Comment by m-m-adams** [comment]
Do we want to block this release? I believe scrolling synth presets occasionally causing cluster problems exists in 1.0 and official 4.1.4 as well

**Comment by m-m-adams** [comment]
Removing the check for 1.1 - it'll leak memory but only 2 clusters and only specifically when changing presets involving samples while playhead is running and a note is playing, which I think is acceptable for now (though eventually we should fix the core problem)
