### ISSUE TITLE
Holding top sidebar value then switching sidebar mode should not cause latching.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2064]
### Please describe the problem:

If you hold the top sidebar pad then turn the `<>` encoder to switch to a different sidebar mode, velocity stays latched to 127, the topmost value you pressed before switching. You can confirm this by either setting the adjacent sidebar's mode back to velocity and see it's set to 127, or simply recording after switching modes and checking note velocity.

### What is the expected behavior?

The value shouldn't latch since a user is forced to press that topmost pad to switch modes. It should switch back to the previous (or default) latched setting.

This is only an issue for Velocity and Modulation.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

1.1.0-beta-F4A2506

**Comment by m-m-adams** [comment]
Clarity: it's latched until you next enter velocity/mod wheel
