### ISSUE TITLE
Some steps on MIDI tracks play ahead of the clock after Deluge has been on for a while.

### ISSUE THREAD

**Issue by voltagecontrolled** [SynthstromAudible/DelugeFirmware#2123]
### Please describe the problem:

When sequencing external MIDI gear on 1.2, I've noticed if I leave the Deluge on for a while, the timing of MIDI tracks will get messed up. Steps will jump ahead of the clock periodically. This does not happen with internal tracks. Have not tested CV tracks. 

If you save the song and power cycle the Deluge and reload the song, the timing is fine. I have only tested this via the DIN output, I have not tried via the USB output. I've reproduced it with a few different sound modules, so I am relatively sure it's the Deluge.

I'll include a video, however note that there's a clicking sound in the background that's NOT the Deluge. Only the kick/snare is coming from a module sequenced by Deluge.

Video Link: https://youtu.be/TNzCfq0H4MY

### What is the expected behavior?

Expectation is that steps play as configured on the grid

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_05_31-1341034

### If possible provide the steps to reproduce the issue and upload additional media:

- Create a MIDI clip and program some notes
- Play the sequence and verify it sounds as expected
- Step away for a few hours
- Come back and play the sequence
- The timing of the MIDI clip(s) will be off. Some steps will play before they are supposed to.
- Save the song, reboot Deluge, and reload
- Timing should be back to normal now.

**Comment by m-m-adams** [comment]
This should be fixed now - I think it's the same issue as #2305
