### ISSUE TITLE
saving synth from kit saves to wrong location

### ISSUE THREAD

**Issue by lmcmulle** [SynthstromAudible/DelugeFirmware#2127]
### Please describe the problem:

synth is saved in the “songs” path not the “synths” and is thus unloadsble

when saving a synth from a kit by pressing shift-aud-save 

### What is the expected behavior?

should save in synths path 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

from about 2 weeks ago

**Comment by sapphire-arches** [comment]
Please retest with a newer nightly, we fixed a bug related to this recently.

**Comment by m-m-adams** [comment]
Any update? This seems fixed when I check it

**Comment by lmcmulle** [comment]
tested the jun19 nightly build this resolved.
