### ISSUE TITLE
Bug (small): gate4 setting displays gate3

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#2153]
### Please describe the problem:

small error in the display of Gate-Out settings: it displays gate3 when selecting gate 4

![IMG_9582](https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/d3076a3d-9909-4ded-a07c-51778026a268)
![IMG_9581](https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/184222b5-2adc-46c0-a351-dd9fa0e5274a)

### What is the expected behavior?

showing gate4 output setting 

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

1.1 RC3

### If possible provide the steps to reproduce the issue and upload additional media:

- go into settings
- gate
- gate output4

**Comment by mnantel** [comment]
Fixed in #2181.
Locally built and tested. Menu title now correctly reflects the physical gate number.
