### ISSUE TITLE
Default Velocity nor current velocity are not respected in Velocity Sidebar mode.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2156]
### Please describe the problem:

1) Upon entering Synth Keyboard Mode, the current Velocity value is not lit up on the Velocity Sidebar (it just has the bottom most pad lit).

2) Default Velocity is factory set to a value of 64 (or 65, can't remember). If you have Momentary Velocity enabled, holding a pad in velocity sidebar and releasing it will latch it back to this value. However, if you set your default velocity in the settings to any other value, like 30 or 115, the velocity sidebar will continue to 'release' the velocity back to the middle, instead of the default velocity the user sets.

3) When a user changes the velocity of the note via the piano roll, that becomes the 'current velocity value'. All notes auditioned via audition pads or synth keyboard pads will normally play at that velocity. However, Velocity Sidebar will not update to this value and if you play notes in the Synth Keyboard View, it will play it at whatever the Velocity Sidebar was set to.

### What is the expected behavior?

1) Velocity Sidebar should display the correct lit pad for the current velocity before any notes are played or velocity values are changed.

2) Velocity Sidebar should be aware of the default velocity the user sets and know to release it to that value if Momentary Velocity is Enabled.

3) Once the user has adjusted velocity within a clip in the clip view (by adjusting a note's value or by pressing and holding a note to 'capture' it's velocity), the velocity sidebar should update it's default velocity to that value, similarly to how velocity behaves in a clip view.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

other

### What is the firmware name:

1.1 RC-3

**Comment by m-m-adams** [comment]
I don't know that this is a bug, they represent different things. I personally wouldn't want changing the velocity for sequencing to affect the velocity on the keyboard
