### ISSUE TITLE
Beta 1.1, Midi follow is sending data in Song View affect entire

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#2164]
### Please describe the problem:

While in Song or Grid view with affect entire engaged, I expect the LPF freq knob to not send data to midi follow, but it is sending midi CC 74 through the midi follow channel i have set up (even if i learn the Song's LPF Freq param to a different CC using the Song menu).

### What is the expected behavior?

Affect entire Song/Grid view should not send midi follow CC's out of the Deluge when moving the golden knobs, because those knobs are meant to control the song global fx and not the selected clip sound

### Is there a relevant Pull request?

1.1

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

**Comment by seangoodvibes** [comment]
Confirmed bug from removing midi follow control of song params and not taking that into account with the midi follow feedback.
