### ISSUE TITLE
SAVING A SONG: 'YOU'VE ENCOUNTERED AN UNSPECIFIED ERROR.'

### ISSUE THREAD

**Issue by d-duan** [SynthstromAudible/DelugeFirmware#2178]
### Please describe the problem:

Just tried to save a song, but was shown an error. It reads 'YOU'VE ENCOUNTERED AN UNSPECIFIED ERROR. PLEASE REPORT THIS BUG'

<img width="508" alt="Screen Shot 2024-06-25 at 9 49 12 pm" src="https://github.com/SynthstromAudible/DelugeFirmware/assets/130952623/22a26847-9d61-43ba-8c2d-bf9ff64c70b2">

### What is the expected behavior?

Song should save

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

deluge-v1_1_0-beta+2024_06_25-b11b0c7

### If possible provide the steps to reproduce the issue and upload additional media:

Unsure how or why it happened. Using deluge as normal. Nothing unusual about this new song I worked on; new kits assembled from samples on SD card. No automation or anything yet, just laying down base tracks and tried to save and had this error. I've now abandoned the song and loaded a few others and tried to save them, with the same error preventing me from saving.

p.s. this was the first time I've made a song and tried to save after upgrading from 1.0 to 1.1beta this afternoon, if that helps.

**Comment by seangoodvibes** [comment]
@d-duan thx for reporting this

Have you checked whether you accidentally locked your SD card or whether your SD card is full?

Thanks

**Comment by m-m-adams** [comment]
Confirmed on the beta from today that I can still save songs. I'm not sure what this error means but I'd try checking your SD card in a computer and make sure it's ok

**Comment by d-duan** [comment]
Appreciate you trying to reproduce it! Yea, it's a strange one. It's the same FAT32 card I've been using. I'll try a different card and see if it makes any difference

**Comment by m-m-adams** [comment]
Are you sure it's not exfat? They're compatible for the first 32gb written but then experience weird errors on deluge. Someone on the discord had that happen before

**Comment by d-duan** [comment]
@m-m-adams hey. Yes, can confirm it's FAT32, and not reaching 32gbs on space used.

**Comment by sichtbeton** [comment]
had this error too saving a song. 256gb card, fat32, 32kb cluster size.

**Comment by m-m-adams** [comment]
@jamiefaye maybe something in the storage manager changes?

**Comment by m-m-adams** [comment]
Gonna chalk this up to some weirdness with beta and nightly changes unless someone has repro steps
