### ISSUE TITLE
Permanent midi controller global option.

### ISSUE THREAD

**Issue by Maly-Lemire** [SynthstromAudible/DelugeFirmware#224]
Add an option that auto learn a midi controller (Without having to press the learn button) and automatically send to selected channel in clip mode.
I have almost never used my deluge because of that missing feature. Having to unlearn and relearn every time I switch track for controlling many external synths is a pain and make the deluge unusable for live performances.

**Comment by weavermedia** [comment]
Sounds a lot like this work in progress [Default midi mapping for currently selected clip](https://github.com/SynthstromAudible/DelugeFirmware/issues/216)

**Comment by Maly-Lemire** [comment]
Yes sounds a lot like it! Yes or could set only to one channel in options. All I want is that when I select a clip it output on that midi channel instantly and in song or arrange mode does nothing.

**Comment by Maly-Lemire** [comment]
It could also use the last selected clip in song and arrange mode if it's not to hard. I would be happy with only on the focused clip.

**Comment by m-m-adams** [comment]
Hi @Maly-Lemire, welcome to the community and thanks for the feature suggestion. Could you close this issue and reopen as a discussion? We are trying to use the issues for bugs and work in progress only

**Comment by Maly-Lemire** [comment]
Closed it but don't know how to re-open as a suggestion...

**Comment by m-m-adams** [comment]
You should be able to open a discussion and one of the options will be feature request. If you refer to #224 in your discussion it will link to this issue

**Comment by Queroland** [comment]
Hey..
sounds like you want midi output for the selected clip?
With #216 I wanted to focus on midi input first to have midi control for the selected clip - on one selectable channel. And work out a fixed midi table for that - without learning functions to keep it simple for now. And it appears not simple to me...
