### ISSUE TITLE
USB MIDI Clock output is roughly doubled and inconsistent c1.1

### ISSUE THREAD

**Issue by konkrete** [SynthstromAudible/DelugeFirmware#2274]
### Please describe the problem:

Example:
Chosen tempo in Deluge is 100bpm, sent factual clock tempo red by ShowMIDI is 195.8bpm.
Strange one: Automatically detected tempo by synced Bitwig is 100bpm, however factual playback of clips in Bitwig is much faster and looks and sounds like almost 200bpm, that is confirmed by ShowMIDI.

### What is the expected behavior?

Expected working properly, sending proper clock signal.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

c1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

Turn On, press Play.

**Comment by sapphire-arches** [comment]
Sounds like showmidi is listening to both virtual cables. Either select only one port, or disable clock output on one (under settings>midi>devices)

**Comment by m-m-adams** [comment]
Confirmed show MIDI doesn't differentiate between the cables. You can stop the extra clock on the deluge side by going to midi->devices->upstream2->clock and set to off, or you can make sure your daw is only receiving clock from one port

**Comment by m-m-adams** [comment]
@konkrete if you're on mac remove and re add the deluge in MIDI studio
