### ISSUE TITLE
fw1.1 in automation view, the selected parameter name doesn't update on the 7seg display when play is on when using shift + pad press

### ISSUE THREAD

**Issue by entzmingerc** [SynthstromAudible/DelugeFirmware#2276]
### Please describe the problem:

In automation view, when you select a parameter, it shows the automation and display the name of the parameter in the display. When play is off, you can use the button combo [shift] + [shortcut pad] to select a automatable parameter. The bug is that when play is on and you use the button combo [shift] + [shortcut pad] to select a parameter, the automation data is shown on the pads for the selected parameter, but the displayed name on the 7seg or OLED isn't updated for the newly selected parameter. 

This works as intended if playback is off. 

### What is the expected behavior?

When I press [shift] + [shortcut pad] to select a parameter in automation view, it should display the parameter name on the 7seg or OLED regardless of playback state. 

### Is there a relevant Pull request?

unknown

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

deluge-c1_1_0.bin

### If possible provide the steps to reproduce the issue and upload additional media:

1) go to automation view in a clip
2) with playback OFF, use [shift] + [shortcut pad] to jump between parameters, note how the displayed parameter name is updated when you switch parameters
3) turn playback ON
4) use [shift] + [shortcut pad] to jump between parameters and the displayed name will not be changing from the last value it was before pressing play

**Comment by seangoodvibes** [comment]
Fixed by #2459
