### ISSUE TITLE
Audiobus tempo not syncing with Deluge MIDI clock on firmware 1.2

### ISSUE THREAD

**Issue by schlesstones** [SynthstromAudible/DelugeFirmware#2305]
### Please describe the problem:

In Firmware 1.1, I can send MIDI clock to Audiobus running on my iPad and it will immediately will sync up to the correct tempo.  However, using the exact same Audiobus setup when I try nightly build 1.2 the tempo is very slow to respond and often does not converge to the correct tempo.  

I don't have a way to accurately measure MIDI clock Jitter directly, so I can only report what happens in Audiobus.

### What is the expected behavior?

When set up to do so, clock on Audiobus should follow Deluge MIDI as it does with Firmware 1.1

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_07_17-dc7c128.bin

### If possible provide the steps to reproduce the issue and upload additional media:

1. Using Audiobus on iPad, set MIDI clock Sync to recieve Midi clock from Deluge
2. Turn on Deluge
3. Press Play
4. In firmware 1.1, notice that Audiobus clock syncs immediately to Deluge tempo
5. Turn tempo knob, and notice that Audiobus clock follows swiftly to the correct tempo
6. Repeat 4 and 5 with 1.2 nightly build
7. Notice that the tempo in Audiobus meanders and does not sync up properly

It seems like it could be a MIDI clock jitter issue but I don't have a good way of measuring this directly.  Thanks!!

**Comment by m-m-adams** [comment]
Should be fixed now if you build from source or grab the nightly build in a few hours
