### ISSUE TITLE
Qued clip in grid view affects vu 

### ISSUE THREAD

**Issue by Exmpl-xe** [SynthstromAudible/DelugeFirmware#2321]
### Please describe the problem:

In Grid view a clip queued for launch visualy affects vu (flashes with the clip)

### What is the expected behavior?

Vu meter being consistent 

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

C1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

1.power 2.enter song view & change to grid view 3.activate vu either before or after a clip is currently being qued to launch.

**Comment by m-m-adams** [comment]
Looks like drawing the flashing square is erasing the sidebar and not triggering a redraw of the vumeter
