### ISSUE TITLE
Unable to load samples into "ghost" KIT rows.

### ISSUE THREAD

**Issue by wesellspatulas** [SynthstromAudible/DelugeFirmware#2346]
### Please describe the problem:

Pressing an unused row's GRID pad (in a Kit, clip view) directly above or below a sample-populated row creates a "ghost row" into which a sample cannot be loaded. The MUTE pad is lit, but pressing the AUDITION pad seems to do nothing.

AUDITION+LOAD brings up the song load menu instead of sample selection,
AUDITION+pushedVERTICAL doesn't euclidean sequence.

In the latest official release an empty row can be selected with AUDITION pad, screen says "NONE" and loading a sample into it works just fine.

I'm guessing this is somehow related to
https://github.com/SynthstromAudible/DelugeFirmware/issues/2157
and/or the kit keyboard view.

### What is the expected behavior?

An empty "ghost row" (ie a kit row with a mute light but no sample) can be selected with AUDITION pad and a sample loaded into it.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_07_28-40c364d

### If possible provide the steps to reproduce the issue and upload additional media:

1. create a kit clip
2. press a GRID pad right above or below the populated kit rows
3. try to select the newly created row with AUDITION pad

**Comment by m-m-adams** [comment]
Confirmed, super weird
