### ISSUE TITLE
USB MIDI not usable when on battery, even with self-powered devices

### ISSUE THREAD

**Issue by YPares** [SynthstromAudible/DelugeFirmware#2349]
### Please describe the problem:

I understand that the Deluge cannot power USB devices when it is not itself plugged in.
However, some devices have their own power and therefore don't need the Deluge to power them, and do not necessarily have a MIDI DIN connection. But the Deluge doesn't establish the connection at all when on battery.
For instance, I'm connecting my Roli Lightpad block (which has its own battery), and the Deluge doesn't detect it. This is not very convenient for nomadic uses.
Is this a hardware limitation, or is it something that could be alleviated?

### What is the expected behavior?

The Deluge should establish MIDI connection, and just not send power to the device.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.1/Beethoven

**Comment by m-m-adams** [comment]
This is sadly a limitation of the lightpad. Powered usb midi devices that don't check for host power before connecting work fine
