### ISSUE TITLE
OLED Frozen at Startup Screen

### ISSUE THREAD

**Issue by requiets** [SynthstromAudible/DelugeFirmware#2369]
![unnamed](https://github.com/user-attachments/assets/12df114c-302b-4654-96d5-5fe40f9ee826)
### Please describe the problem:

Screen frozen at Deluge logo. Can grid still functions but screen does not change. Occurred with July 31st nightly and July 29th nightly. Firmware was recognized as being updated successfully.

### What is the expected behavior?

OLED moves to menu after startup screen

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_2_0-nightly+2024_07_29-08a7713

**Comment by m-m-adams** [comment]
We're aware but the cause is a mystery, it comes and goes between nightly builds at the moment
