### ISSUE TITLE
Debug text file helper 

### ISSUE THREAD

**Issue by Queroland** [SynthstromAudible/DelugeFirmware#239]
Hey,

is there any text logger tool in the code?
I don`t have jlink and want to write a textfile to see whats going on in the deluge. I couldn`t find something.

How do you do if you don`t have jlink?

Thanks.

**Comment by m-m-adams** [comment]
Yes - debug::println output will show on the physical MIDI port as uart messages as well as the third usb MIDI port

**Comment by Queroland** [comment]
Ah, interesting! I`ll try.. Thank you!
