### ISSUE TITLE
Can't delete a single kit row in C1.1.0

### ISSUE THREAD

**Issue by MkUltra85** [SynthstromAudible/DelugeFirmware#2422]
### Please describe the problem:

I'm trying to delete a kit row from a kit; if I hold the audition pad for a kit row and press the SAVE/DELETE button, it brings up the "SAVE SYNTH" menu, but does not delete the kit row. This is of course in a KIT and not a SYNTH. This seems to happen regardless of anything else I do.

### What is the expected behavior?

Delete the kit row

### Is there a relevant Pull request?

I don't believe so

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

C1.1.0

**Comment by m-m-adams** [comment]
Not  a bug, the command to delete a kit row is to hold a pad in the row and press delete

**Comment by m-m-adams** [comment]
audition+save is to save the kit row as a synth for later use

**Comment by MkUltra85** [comment]
Hah, oops. I would swear I tried that, too, but it's working now.
