### ISSUE TITLE
Clip is not selected after creation 

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#2428]
### Please describe the problem:

If you continue holding the clip while in the creation menu it is not selected after exiting the menu and requires an extra press to select

### What is the expected behavior?

When the clip is created it would also be selected and in the UI mode CLIP_PRESSED_IN_SONG

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by seangoodvibes** [comment]
Fixed by #2429
