### ISSUE TITLE
VisualStudio instead of E2 Studio

### ISSUE THREAD

**Issue by Queroland** [SynthstromAudible/DelugeFirmware#244]
Hello,

is it possible to use Visual Studio? I don`t use jlink.

As a C# guy this all is really painful.
What installations are needed?

Thanks!

**Comment by m-m-adams** [comment]
Hi queroland, feel free to reach out in the dev support section of our discord - https://discord.com/channels/608916579421257728/1129138982198984825. There's a vscode config in the repo and dbt will set you up automatically to do commandline builds

Github issues are for bug reports and work in progress

**Comment by Queroland** [comment]
Ouh, thank you!
