### ISSUE TITLE
Drum Randomizer should ignore  Mac .dot files

### ISSUE THREAD

**Issue by stirman** [SynthstromAudible/DelugeFirmware#2463]
### Please describe the problem:

Just reorganized all my drum samples to take advantage of the Drum Randomization community feature, which was such a good idea! I renamed all samples in each folder numerically (1.wav, 2.wav, etc).

But, when I hold hit AUDITION + RANDOM, it sometimes loads "._#.wav" (._1.wav, ._57.wav, etc.) which are hidden mac files in that directory, which don't contain any audio, so the drum randomizer has ~50% of actually working.

[BONUS IDEA!] Respect the setting to audition samples that the deluge already has, where you can set to always audition, or audition only if playback stopped, so if playback is stopped... audition the sound when RANDOM is pressed. Thx!

### What is the expected behavior?

AUDITION + RANDOM selects a news sample from the directory the pad's sample is in, ignoring the mac .dot files ("._blah.wav")

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

c1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

Mac only
1. Initialize a new kit
2. Load a sample from a directory that has other samples in it
3. Hold [AUDITION] + [RANDOM] to randomize the sample
4. Check display to see if an actual sample was loaded, or if a .dot file was loaded erroneously

**Comment by M0R172** [comment]
Bug should be fixed by PR #2470 

The Bonus Idea is great, but I have no time for that right now - maybe re-post that separately as a feature request?
