### ISSUE TITLE
Missing documentation for clip names feature

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#2496]
### Please describe the problem:

Clip names feature is not documented https://github.com/SynthstromAudible/DelugeFirmware/pull/2293

### What is the expected behavior?

Every feature is documented

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Built from community

**Comment by KrisGelero** [comment]
PR created :)
