### ISSUE TITLE
Errors and freeze on song load with beta 08_28

### ISSUE THREAD

**Issue by Balistix55** [SynthstromAudible/DelugeFirmware#2514]
### Please describe the problem:

These songs were made in beta 08_09_9fbd773. Now I saved them using Beethoven 1.1.1, where I can open and play them without issues. But in the latest beta 2024_08_28-1bf601b is not possible to load them, because of error and freeze.
Photos were posted on Discord

### What is the expected behavior?

Load songs and play them without deluge freeze and errors.

### Is there a relevant Pull request?

no

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_08_28-1bf601b.bin

### If possible provide the steps to reproduce the issue and upload additional media:

https://drive.google.com/file/d/1NC4jOudhFO2jZULcF32T-e3n8xbgLtGu/view?usp=drive_link
https://drive.google.com/file/d/1S1hyyPp1E13e_OrOGuICaHwMj8JnPbLo/view?usp=drive_link

**Comment by m-m-adams** [comment]
I've just checked both songs and they're working in both nightly and beta (checked debug and release builds just in case) 

Can you try these exported copies and see if they'll load on your deluge?

**Comment by Balistix55** [comment]
I will try it next day

so 31. 8. 2024 v 20:17 odesílatel Mark Adams ***@***.***>
napsal:

**Comment by Balistix55** [comment]
@m-m-adams I checked beta 09_01 - error e365 during loading of song Breathe and freeze. Also second song with freeze.

But then I checked nightly 09_01 and songs are loaded and played properly without error or freeze. Also other songs that gives an error on song load are without any error or freeze.

**Comment by m-m-adams** [comment]
Hm they definitely work here. Maybe it's something with the filepaths that isn't hit when using the exported versions.
Since your deluge has the files I don't think it'll load from the exported/'collect all' location

I'll try moving them into their original locations and see if the bug triggers

**Comment by m-m-adams** [comment]
@Balistix55 it looks like the problem is some of the files have .wav in them twice ("SAMPLES/Balistix/Artwork/Breathe/Breathe.wav_bass_2.wav" and "SAMPLES/Balistix/Artwork/Breathe/Breathe.wav_drums_3 tympany.wav"), I'd try renaming them

**Comment by Balistix55** [comment]
@m-m-adams Oh, I will rename these samples. I did not mention these double wav names 👍🏻👋🏻

**Comment by Balistix55** [comment]
@m-m-adams I checked the newest beta and songs loading is stable without errors 👍🏻

**Comment by m-m-adams** [comment]
Ok great, thanks for checking!
