### ISSUE TITLE
Can't create new clips in grid mode

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#2518]
### Please describe the problem:

I was able in grid mode after creating and deleting audio clips, to make the grid mode enter a state where tapping an empty pad doesn't popup the menu to create new clips, when you let go the pad, the new clip doesn't remain, it goes away.

There must be some code path that takes the grid into a state where it is impossible to create new tracks. Can't reproduce it right now but I am trying to do it.

### What is the expected behavior?

new tracks can be created in grid mode

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

**Comment by m-m-adams** [comment]
Hopefully fixed by one of the other grid fixes?
