### ISSUE TITLE
old screen not booting up 

### ISSUE THREAD

**Issue by TwoToneProductions** [SynthstromAudible/DelugeFirmware#2548]
### Please describe the problem:

when loaded new firmware the screen is blank or does not load up

### What is the expected behavior?

no
[1.pdf](https://github.com/user-attachments/files/16828778/1.pdf)
[screen.pdf](https://github.com/user-attachments/files/16828779/screen.pdf)

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly, Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_09_01-e1862cc.bin

**Comment by m-m-adams** [comment]
Closing as a duplicate
