### ISSUE TITLE
Audible artifacts (clicks/pops) when saving a song while synth voices/kits are playing.

### ISSUE THREAD

**Issue by douglas-carmichael** [SynthstromAudible/DelugeFirmware#2549]
### Please describe the problem:

When you save a song while synth voices/kits are playing, you can hear audible artifacting (clicking/pops) after pressing "SAVE" at the song name screen.

### What is the expected behavior?

Uninterrupted audio when saving a song.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly, Beta

### What is the firmware name:

1.2.0-BETA-E1862CC

### If possible provide the steps to reproduce the issue and upload additional media:

1) Create a synth or kit track with notes on it.
2) Press "PLAY".
3) While playing, save your song. Observe the audio artifacting.

**Comment by m-m-adams** [comment]
It's song culling from the extra SD card load, I don't know if we have a good way to fix this
