### ISSUE TITLE
"Empty pad to unarm" is not working as before. It makes "Empty pad to Create+Record" not work

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#2554]
### Please describe the problem:

I remember that some builds ago I could have both settings enabled (Press empty pad to unarm, and Create+Record). Now with both enabled Create+Record doesn't work

### What is the expected behavior?

In grid mode, when Record is NOT enabled, pressing an empty pad unarms (mutes) the track, and when Record is engaged, pressing an empty pad then creates a clip and arms it to record. That is, making use of the Record button state to differentiate which of the two actions to do when pressing the empty pad, which is the behavior that it had some weeks ago

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

**Comment by m-m-adams** [comment]
I think unarm wins unless recording is active, have you tried that?
