### ISSUE TITLE
CROSS-SCREEN pad won't activate with longer press/holds

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2556]
### Please describe the problem:

For normal use of cross-screen (sequencing notes for multiple pages at a time), cross-screen won't activate when pressing the pad unless a short press is made, in my case, a very short press. Before investigating, I just assumed cross-screen didn't work in clip view, it does, but needs to be pressed quickly.

### What is the expected behavior?

CROSS-SCREEN should activate on any type of pad press while in clip view, not just a quick press.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.2 from 8/29

**Comment by seangoodvibes** [comment]
As discussed, pressing cross screen should always toggle cross screen on release unless you've performed another action while holding cross screen.
