### ISSUE TITLE
Clock toggle wont save on midi device

### ISSUE THREAD

**Issue by mcabrerapf** [SynthstromAudible/DelugeFirmware#2578]
### Please describe the problem:

On the `Settings>MIDI>Devices>YOUR_MIDI_DEVICE>Clock` option, if I toggle it of all works well, however when turning the deluge on and off I can see that the setting is not saved so it is always on.

### What is the expected behavior?

Clock toggle should save its value and persist after restarting deluge

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_09_04-c43c8cc

**Comment by m-m-adams** [comment]
Hm yeah it's possible it's only saved in flash (so just for the upstream USB ports)
