### ISSUE TITLE
MPE midi clip issues when using usb hub

### ISSUE THREAD

**Issue by mcabrerapf** [SynthstromAudible/DelugeFirmware#2580]
### Please describe the problem:

Some notes get stuck (possibly note on/off messages getting lost) when using an mpe midi clip that is sent through the deluge usb into a usb hub which then goes to a synth (hydrasynth in my case)

### What is the expected behavior?

No dropped notes on mpe clips

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_09_04-c43c8cc

### If possible provide the steps to reproduce the issue and upload additional media:

Using the following songs and settings found here https://drive.google.com/drive/folders/1v566dA2EL0pHp6gZpDIAwVmTVom9R4iD?usp=sharing

Open either song `Mpet` or `Mpet2` which contain a single bar mpe lower midi clip.
I have my synth (hydrasynth or micromonsta2) conected to a usb hub which goes into deluge usb.
MPE settings are Lower => 7
I can clearly hear a lot of lost notes or stuck notes when playin back the clip

**Comment by m-m-adams** [comment]
Confirmed, happens to me too. I'm not sure how/why this is happening yet but it seems to be somehow related to sending clock

If I disable the clock on all the usb devices on the hub then it works fine, so I'd suggest that as a workaround for now
