### ISSUE TITLE
Can't rename MIDI and CV tracks from Arranger View

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#2587]
### Please describe the problem:

Can't rename MIDI and CV tracks from Arranger View

### What is the expected behavior?

Can rename MIDI and CV tracks

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

**Comment by sinewave440hz** [comment]
Not sure if useful but also reproducible on 7SEG.
