### ISSUE TITLE
Menus with chevron and check marks have titles cut off earlier than needed

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2631]
### Please describe the problem:

Menus with chevron and check mark icons on the right hand side also have a gap between the end of the title and the icon.

### What is the expected behavior?

![IMG_7470](https://github.com/user-attachments/assets/34999a5f-54fe-43f4-a7f3-09abd7ef64c8)

The red space marked above could be filled out more. I think one extra character can fit while still leaving a little space before the icons. This would partly reduce the need of scrolling and look more presentable/intentional imo.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.2-beta

**Comment by seangoodvibes** [comment]
Agreed, I'll fix this
