### ISSUE TITLE
Preset and sample browser should have the inverted highlighted section extended by 1px.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2632]
### Please describe the problem:

The inversion occurs at the same point as the first pixel of the first character. Depending on the character, it can make no left inverted border present.

![IMG_7472](https://github.com/user-attachments/assets/4cb2521b-3a43-4367-8525-5c27395f7503)

### What is the expected behavior?

The inverted area should be extended 1px to the left of the title's start point. This will be consistent with how the bottom and top of the highlighted inversion has a 1px space of white around the text.

Super minor no doubt, but this would make things a hair more presentable.

This has always been present in any OLED firmware.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

**Comment by seangoodvibes** [comment]
Agreed will take care of this too
