### ISSUE TITLE
Chopin - audition pad deactivates with sticky shift engaged when editing a synth.

### ISSUE THREAD

**Issue by A-Beep-creator** [SynthstromAudible/DelugeFirmware#2680]
### Please describe the problem:

Chopin - audition pad deactivates with sticky shift engaged when editing a synth.

### What is the expected behavior?

To be able to audition synth parameters without play running.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

Chopin

### If possible provide the steps to reproduce the issue and upload additional media:

1. Create new synth.
2. Engage sticky shift.
3. Tap audition note and receive no sound.
4. Work around has been to create sequence and run play.

**Comment by seangoodvibes** [comment]
Sticky shift is the same as holding shift.

Shift + audition pad = silent audition.

It's not a bug.
