### ISSUE TITLE
Bug with "Copy Clips" in Grid View Green Mode

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#2693]
### Please describe the problem:

Noticed that you can get stuck in UI_MODE_CLIP_PRESSED_IN_SONG_VIEW with "Copy Clips" pop-up stuck on the display

Steps to re-produce:
- Go into green mode in song grid view
- Press the grid to create a whole bunch of clips
- Try to create clips in multiple pads by pressing pads adjacent pads together
- You'll see that if you do it often enough you'll eventually get stuck with "copy clips" on the display

### What is the expected behavior?

Proper handling of multiple pad presses so that you don't get stuck in a UI mode

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### If possible provide the steps to reproduce the issue and upload additional media:

https://github.com/user-attachments/assets/f1790857-e801-418b-b919-e521265f7d83

**Comment by m-m-adams** [comment]
repro is just press a second pad while the clip creation menu is still open on the first one

**Comment by seangoodvibes** [comment]
> repro is just press a second pad while the clip creation menu is still open on the first one

that doesn't seem to be it as this happens when I press multiple pads to create new clips in existing tracks

**Comment by m-m-adams** [comment]
It definitely is. It reproduces the bug 100% of the time

**Comment by RJ-Eckie** [comment]
Easier way to reproduce this:
- press existing clip pad
- press empty clip pad
- release existing clip pad
(1.3.0-DEV-E509B77E)

https://github.com/user-attachments/assets/f273291c-8bc5-473e-826c-f8b542b33426

UI expects the second press to be released first, COPY CLI

Popup stays open when first press is released first instead.
Doing a succesful copy restores normal behavior
