### ISSUE TITLE
 Automations recorded/entered disappear on song reload.  (vol & pan; modFX rate; reverb depth; master pitch; decimation; bitcrush)

### ISSUE THREAD

**Issue by percussijan** [SynthstromAudible/DelugeFirmware#2710]
### Please describe the problem:

Above parameter automations do not save with the song. After song reload all recorded or manually entered automations are gone except delay time/rate and filter cutoff/resonance. 

### What is the expected behavior?

All automations save with the song and are still there after song reload.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.2.0-NIGHTLY-5264A54

### If possible provide the steps to reproduce the issue and upload additional media:

Enter or record automations in song or clip view. Save song. Reload song.

**Comment by m-m-adams** [comment]
Confirmed - seems to be generally failing to save anything other than the base parameter values. Modifying these parameters between clips is also not saving

**Comment by m-m-adams** [comment]
Actually I think they might be entirely unsaved
