### ISSUE TITLE
Tempo display on song/arranger view not showing external tempo when Deluge is set to follow external clock 

### ISSUE THREAD

**Issue by solaris76** [SynthstromAudible/DelugeFirmware#2736]
### Please describe the problem:

When the Deluge is sync'd via external clock the display does not update to show the external sync'd tempo. (either via CLK IN or MIDI Clock). 

NOTE: In FW1.1 the CLKIN does impact tempo display when tapping the tempo knob, albeit not via MIDI clock. 

### What is the expected behavior?

Tempo display adjusts based on the externally set tempo. Ideally in realtime or, worse case via a refresh when entering or exiting a clip for example. 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.1/Beethoven, Beta

### What is the firmware name:

1.2 Chopin Beta 

### If possible provide the steps to reproduce the issue and upload additional media:

1. Set MIDI>Clock>INPUT = ON
2. Start Deluge play via external MIDI device (sending MIDI Clock)
3. Change tempo on external MIDI device 
4. Tempo display doesn't adapt to external tempo.

**Comment by davidvandenbor** [comment]
This either still persists or it “started again” with the nightly build “deluge-v1_3_0-nightly+2025_04_02-cc9091b”. I connected a Pioneer DJS-1000 sampler as an external master. When the tempo is sent to the deluge, the deluge plays in sync. But the tempo displayed on the Deluge's OLED screen is not the same tempo as displayed on the DJS.

For instance, the tempo sent from the DJS is 117. The OLED screen on the Deluge says "123" but the Deluge plays in sync @ 117.
