### ISSUE TITLE
Cannot convert empty synth kits to kit clips on nightly

### ISSUE THREAD

**Issue by abstractrealism** [SynthstromAudible/DelugeFirmware#2747]
### Please describe the problem:

Just downloaded the latest nightly to try out Sean's new note probability/iterance view, went to make a kit clip to try it out, and could not. Pressing "Kit" does nothing. Pressing Midi and CV work. Pressing Kit when there are notes present says "Clip not empty" (think that's new?), but even when it's empty, can't switch to Kit. 

### What is the expected behavior?

1. Press Kit
2. Have a kit clip
3. ???
4. Profit

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_3_0-nightly+2024_10_02-364dcff

### If possible provide the steps to reproduce the issue and upload additional media:

1. Turned on
2. In default empty template song, pressed Kit
3. Couldn't get a kit

**Comment by m-m-adams** [comment]
Thanks for the report - just tested and creating kit clips works fine, converting empty synth clips to kit clips is not working
