### ISSUE TITLE
Mutable Reverb model is enabled regardless of which model was saved in a given song

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2758]
### Please describe the problem:

Was playing old songs and they didn't sound the same. Looks like they all used the FREEVERB reverb originally, but MUTABLE is the model enabled.

### What is the expected behavior?

Have the reverb model saved to the song switch to that reverb. Seems like Mutable is default universally currently.

### Is there a relevant Pull request?

possibly? #2404

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.2

**Comment by m-m-adams** [comment]
I can't reproduce, saving and loading songs with freeverb is working fine. Can you share the song please? (just the xml is fine)

**Comment by m-m-adams** [comment]
Occurs on songs from official 4.1.4 and community 1.0, the check eliminated too many versions
