### ISSUE TITLE
Auditioning a pad while the MIDI PRESET browser is open and unpopulated will display an error message.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2763]
### Please describe the problem:

Normally when any preset browser (SYNTH, KIT) is open, the rightmost sidebar column is still active and can be used to audition any notes/kit rows while browsing.

When you hit LOAD+MIDI and the MIDI PRESET browser appears. **If you haven't populated the midi browser at all**, pressing the sidebar will display the following message: "You've encountered an unspecified error. Please report this bug."

### What is the expected behavior?

Either display "File not found." which is displayed when you enter an empty synth/kit/(and even midi) folder and try to audition that pad or simply allow midi messages to be still sent.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.2-beta

**Comment by m-m-adams** [comment]
This seems to be working fine for me - what are the full steps? 

If I make a midi clip and then try to load a midi preset the audition pads work fine, even if there isn't a preset to load
