### ISSUE TITLE
Extra vertical line next to folder icon when in midi preset browser

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#2765]
### Please describe the problem:

![IMG_7640](https://github.com/user-attachments/assets/bada7c54-5460-4001-a14f-488485172ee5)

there's an extra vertical line next the the folder icon, only when in the midi browser. i imagine this is related to making the midi preset icon display properly since it's an extra pixel longer than other icons

### What is the expected behavior?

no extra vertical line at the right edge of the folder icon

### Is there a relevant Pull request?

2613

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.2-beta

**Comment by m-m-adams** [comment]
I think it might be rendering both? It looks like a circle behind the folder too
