### ISSUE TITLE
In arranger white clips are very dim

### ISSUE THREAD

**Issue by bzawad** [SynthstromAudible/DelugeFirmware#2778]
### Please describe the problem:

In arranger mode, white clips appear very dim for buttons after the first one in the clip, making them difficult to see. While increasing the brightness to the maximum helps, at lower brightness levels, the clips are still hard to distinguish. This makes it challenging to gauge the length of the clip. The issue seems to have started with firmware version 1.2.0, and it was not present in version 1.1.1.

### What is the expected behavior?

In arranger mode, white clips should be brighter so they're visible even with lower brightness settings.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_10_05-4551624.bin

### If possible provide the steps to reproduce the issue and upload additional media:

Create a clip in song mode.  Go to arranger and create an extended clip.  Now convert the extended clip to a white by holding shift and pressing the first button of the clip.  The buttons following the first button will be very dim.

**Comment by m-m-adams** [comment]
@seangoodvibes looks like using the tail colour for white dissapears at about 60% brightness
