### ISSUE TITLE
Synth patch selector won't go past 13th sound

### ISSUE THREAD

**Issue by phpguru** [SynthstromAudible/DelugeFirmware#2847]
## Issue
* Attempting to select a synth and scrolling clockwise (incrementing patch numbers) somehow its going from 13 back to 1

## Workaround
* I can scroll backwards from the end (anti-clockwise) and it goes from patch 1 to 170 no problem

## demo
https://www.facebook.com/1133605035/videos/1283018662891672/

## Expected behavior
* scrolling clockwise increments patch numbers 1 ... 170 and then starts over at 1

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

Firmware 1.2.0-beta-c43c8cc

### If possible provide the steps to reproduce the issue and upload additional media:

After reboot I am able to reproduce

**Comment by ok-reza** [comment]
could you share a screenshot of your SYNTH sd card contents, just want to see if there's anything weird in there. make sure to make visible any hidden files too (eg. any mac-based files starting with ._)

**Comment by m-m-adams** [comment]
Closing for now, will reopen if we can get a listing of the files
