### ISSUE TITLE
Audio drops out much more frequently while scrolling presets on 1.2 beta than on Official

### ISSUE THREAD

**Issue by abstractrealism** [SynthstromAudible/DelugeFirmware#2848]
### Please describe the problem:

While scrolling through synth presets (did not test, maybe kit presets too) on the community firmware while song is playing, voices in the song drop out much more frequently and consistently than on Official. In the attached videos, the voice that you can easily hear drop out is the long whiney high note. On Official I believe I only heard it drop once, when I first opened the BOD6 folder. On 1.2beta it dropped many times while scrolling through the factory presets, as well as the BOD presets. 

### What is the expected behavior?

I mean, ideally loading the presets wouldn't ever cause playing audio to drop, but at least not much more than on Official. 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_10_29-05b5613

### If possible provide the steps to reproduce the issue and upload additional media:

[Test song.zip](https://github.com/user-attachments/files/17560812/Test.song.zip)

While playing the above test song (apologies, sounds terrible, was just a test), the high notes in the 3rd instrument, 100 Noise Lead, drop out when:

1. Hit Play
2. On a new clip, spin the select knob, or particularly when you hit Load + Synth and scroll that way. 
3. Dropouts occur

For what it's worth, I'm using a SanDisk Ultra 64GB card, rated U1 C10 A1, but I don't _think_ it's an SD card issue since it's the same SD card in each situation. 

https://github.com/user-attachments/assets/8045f4a5-fadf-4381-86ee-eed78b36b873

https://github.com/user-attachments/assets/eb303574-9eed-4ee3-a5fe-4d0c0146f56f

**Comment by m-m-adams** [comment]
Fixed by #3126
