### ISSUE TITLE
Stem Export Silence Threshold is not low enough

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#2867]
### Please describe the problem:

User reported that the silence threshold cut off their delay tail when exporting a track stem from arranger view

### What is the expected behavior?

Threshold for silence should be low enough to not cut off any tails.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

**Comment by m-m-adams** [comment]
Maybe do the same approach as the reverb and always render at least 12 extra seconds?
