### ISSUE TITLE
Audio clip file browser bug

### ISSUE THREAD

**Issue by panicmechanic** [SynthstromAudible/DelugeFirmware#2885]
### Please describe the problem:

When selecting a file for an audio clip: If SHIFT is on, the user recieves a "Can only use for brand new kit" warning, as if the Deluge thinks you're asking it to slice the sample into a kit. 

### What is the expected behavior?

For the sample to be selected and the menu closed. 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### If possible provide the steps to reproduce the issue and upload additional media:

1. Create and enter an audio clip
2. Turn on sticky shift
3. Hit "browse" shortcut
4. Select a file
5. Recieve warning

**Comment by seangoodvibes** [comment]
Fix is here: https://github.com/SynthstromAudible/DelugeFirmware/blob/5d5397a20494304c2c2fc9745f2a0ed6f186e56e/src/deluge/gui/ui/browser/sample_browser.cpp#L375

instead of 

if (Buttons::isShiftButtonPressed()) {

it should be:

if (soundEditor.editingKit() && Buttons::isShiftButtonPressed()) {
