### ISSUE TITLE
Midi Devices Menu in Settings freezes deluge

### ISSUE THREAD

**Issue by entzmingerc** [SynthstromAudible/DelugeFirmware#2933]
### Please describe the problem:

Power on. [Shift] + [Select] to navigate to Settings menu. Scroll to Midi and click select. Scroll to Devices and click Select. Deluge freezes.  

### What is the expected behavior?

Deluge should pull up the Midi Devices menu and not freeze

### Is there a relevant Pull request?

unknown

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

deluge-v1_2_0-beta+2024_11_15-b95d23c

### If possible provide the steps to reproduce the issue and upload additional media:

https://photos.app.goo.gl/azhTWPbQUqhWM3Yy7
Video of steps to reproduce error. 

Power on. [Shift] + [Select] to navigate to Settings menu. Scroll to Midi and click select. Scroll to Devices and click Select. Deluge freezes.

**Comment by stellar-aria** [comment]
Cannot reproduce on latest 1.2 with OLED Deluge

**Comment by entzmingerc** [comment]
discussed on discord: I'm going to wipe SD card and try to reproduce again
