### ISSUE TITLE
MIDI Transpose causes sequences to jump around

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#2936]
### Please describe the problem:

When you use the midi transpose feature while you're in a scale mode instrument clip, the notes currently visible shift out of view make it difficult to edit existing sequences because they aren't constantly shifting out of view

### What is the expected behavior?

Notes get transposed but stay visible so that you can edit them while transposing is happening

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

**Comment by nikodemus** [comment]
Possibly a bad interaction with https://github.com/SynthstromAudible/DelugeFirmware/pull/2364
