### ISSUE TITLE
Crash when saving after changing kit synth preset

### ISSUE THREAD

**Issue by ElVicente** [SynthstromAudible/DelugeFirmware#2948]
I'm on beta from 21 11
It happens every time when I save my project after having changed a kit preset (synth)
Steps to reproduce :
Edit kit clip (3rd collumn/ 3rd clip in grid view)
Select second drum and replace by the RG Dr Snare2.xml drum preset
Got crash and a corrupt empty xml project file.
[Crash deluge.zip](https://github.com/user-attachments/files/17871143/Crash.deluge.zip)

It's my first bug report, I hope it's made correctly and will help! :)

**Comment by m-m-adams** [comment]
Ok looks like it's just because the selected drum is the one that was replaced, needs to be updated to the one that was loaded

As a workaround touch any audition pad before saving for now
