### ISSUE TITLE
Broken string in place of (e.g.) “45% Latching” 

### ISSUE THREAD

**Issue by abstractrealism** [SynthstromAudible/DelugeFirmware#2980]
### Please describe the problem:

Instead of “45% Latching” or whatever other percentage, I’m instead getting a pop up that says “@/ / @“ or occasionally “ / @“ (or it appears in a synth clip to have a > instead of an @ symbol. 
It only shows up upon first scrolling to it. If I let go, then press the note again and turn select, the first thing it says is the correct “45% latching”

### What is the expected behavior?

Normal string displays

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.3.0-Nightly-92A67BF

### If possible provide the steps to reproduce the issue and upload additional media:

Add note to grid. Change probability to a percentage. Add another note. Change its percentage to the same as the first. The latching option appears glitched
![IMG_1574](https://github.com/user-attachments/assets/254b7261-d2f0-438c-9f1f-d52799c50e4f)

**Comment by seangoodvibes** [comment]
Confirmed reproducible 
https://github.com/user-attachments/assets/6c3d5cc9-2f20-4c51-8283-e8640da90a90
