### ISSUE TITLE
Any keyboard view + Record = Crash

### ISSUE THREAD

**Issue by panicmechanic** [SynthstromAudible/DelugeFirmware#2987]
### Please describe the problem:

As above on the latest nightly. 

### What is the expected behavior?

Recording.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

2024_11_28-165f8ab

### If possible provide the steps to reproduce the issue and upload additional media:

1. Open any song/create new
2. Enter synth clip
3. Open keyboard
4. Tap record
5. Tap play
6. Crash

**Comment by panicmechanic** [comment]
If this is just me please lmk, maybe it's something to do with my SD card

**Comment by m-m-adams** [comment]
I can't reproduce this on the latest nightly, I've tried various combos of quantization and count in bars as well as different types of synths

Can you confirm you are able to record on earlier nightlies without issues?

**Comment by seangoodvibes** [comment]
> I can't reproduce this on the latest nightly, I've tried various combos of quantization and count in bars as well as different types of synths
> 
> Can you confirm you are able to record on earlier nightlies without issues?

It's reproducible for me.

Just went into keyboard view, turned on record and hit play.

**Comment by seangoodvibes** [comment]
https://github.com/user-attachments/assets/de050cc2-9a18-4eda-97db-818b87b3a569

**Comment by m-m-adams** [comment]
The bug is only present with "alternative playback start".  It seems to be miscalculating the position to resume from when you're in a clip with the keyboard open
