### ISSUE TITLE
deluge-v1_3_0-nightly+2024_12_07-d8191f4  and distorded sound!

### ISSUE THREAD

**Issue by nicolasbulb** [SynthstromAudible/DelugeFirmware#3027]
### Please describe the problem:

When trying the new deluge-v1_3_0-nightly+2024_12_07-d8191f4 with a Steinway sample, all the sounds are distorded!

### What is the expected behavior?

The sounds of the Steinway Piano should play just fine with the previous alpha: deluge-v1_3_0-nightly+2024_12_06-62fc344

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_3_0-nightly+2024_12_07-d8191f4

### If possible provide the steps to reproduce the issue and upload additional media:

1. Load the Steinway piano sample and then play the piano
2. you'll get the distorted sound.

**Comment by stellar-aria** [comment]
probably caused by #2982, reverted until I have time to work on it. keeping issue open for reference. do you have a copy of the sound/samples that display the issue?
