### ISSUE TITLE
Converting between Instrument and Audio clips breaks Arranger instrument order

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#305]
Either replaceAudioClipWithInstrumentClip or replaceInstrumentClipWithAudioClip or both manipulate the Clips and their underlying Outputs in a way that can lead to different ordering in Arranger and Clip view (and thus later in Grid view). Earliest tested FW is Deluge+firmware+V4p1p4-beta1+OLED.bin

**Comment by m-m-adams** [comment]
I think this can also happen when you rearrange clips in song view, arranger keeps the original order. The fix might be to have arranger view dynamically resort itself to match the order of instruments in song view

**Comment by m-m-adams** [comment]
Won't fix - this actually creates a new instrument so inevitably changes the order. As rows view doesn't have a real concept of tracks there's no clean way to make them match
