### ISSUE TITLE
Ocs Sync issue

### ISSUE THREAD

**Issue by Qui-Gon-JooL** [SynthstromAudible/DelugeFirmware#3058]
### Please describe the problem:

 Hello,
for several nightly builds the OSC Sync no longer works, instead a noisy sound.

### What is the expected behavior?

It should work

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

24-12-11 nightly build

**Comment by Qui-Gon-JooL** [comment]
SYNC mod still not working on deluge-v1_3_0-nightly+2024_12_14-20ad4c9.bin

**Comment by seangoodvibes** [comment]
@Qui-Gon-JooL please use the beta build for now. This will be fixed whenever it gets fixed, sorry but it's the nature of the nightly build, as much as try prevent things like this from happening. The nightly is "experimental" at the moment.
