### ISSUE TITLE
Turning vert. Encoder in velocity view cuts off notes

### ISSUE THREAD

**Issue by pssssssst** [SynthstromAudible/DelugeFirmware#3066]
### Please describe the problem:

When you turn the vertical encoder in velocity view it sometimes cuts off notes

### What is the expected behavior?

Turning vertical encoder doesn't interfere with the notes playing

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

beta 14dez24

### If possible provide the steps to reproduce the issue and upload additional media:

1. Open synth clip.
2. program some longer notes
3. press play
4. enter velocity view
5. turn vertical encoder fast

**Comment by seangoodvibes** [comment]
Thanks for reporting

I don't think we'll have a solution for this for the beta other than:

- not turning the vertical encoder "fast" / turn it slower
- not turning the vertical encoder while playback is running

I'm working on some UI improvements that may help but it won't be part of the 1.2 release.

**Comment by pssssssst** [comment]
No problem.
It doesn't bother me in my workflow at all.

**Comment by m-m-adams** [comment]
Fixed by #3126
