### ISSUE TITLE
sample folders of deleted songs visible on 7seg

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#309]
After deleting a song that has an automatic sample folder from the "collect and save" command, the 7seg deluge still shows the folder. Either it would be deleted with the song (the best behaviour IMHO) or the folder is invisible.

**Comment by m-m-adams** [comment]
This sounds like desired behaviour to me, deleting a song doesn't necessarily mean you want to delete its data

**Comment by sichtbeton** [comment]
When the song is present, the folder is not. When the song is deleted, the folder is present (but empty). So it doesnt add anything, confuses only and was actually tackled by Rohan in one of his fixes. It just didnt translate to the open source version.

So its not by design and a bug.

**Comment by m-m-adams** [comment]
Ah ok

**Comment by sichtbeton** [comment]
> Ah ok

sorry sound too snarky. it's just an annoying thing to not be able to freely skip like it used to be possible (back in the days of 4.0.1 something).

**Comment by m-m-adams** [comment]
Yeah no worries, it's not a feature I use so I wasn't sure what the expected behaviour is

**Comment by sichtbeton** [comment]
This is a regression to the existing fw. I don’t think “future release” is the right category for this.

**Comment by m-m-adams** [comment]
Luckily this is an open source project so anyone is welcome to fix it anyway. It's not ideal behaviour but it is easy to work around.

**Comment by m-m-adams** [comment]
The samples remain in the file - I don't want to delete them, and the folder does exist. We could skip it but I'm not sure that's useful
