### ISSUE TITLE
How to activate Live Input Monitoring?

### ISSUE THREAD

**Issue by Tacosphere** [SynthstromAudible/DelugeFirmware#3171]
### Please describe the problem:

Hi, I've used live input monitoring feature in the past (selectable "live input monitoring") and switched to lastest community nighly build version and recognized it doesn't seem to have live input monitoring feature any more???

### What is the expected behavior?

Live input monitoring should be selectable from input list for all inputs L, R, Stereo.

### When did you start noticing the issue?

With community nightly build 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

1.3.0 2024_12_27-f40cf5e

### If possible provide the steps to reproduce the issue and upload additional media:

learn input + audition pad -> switch input source etc.

**Comment by seangoodvibes** [comment]
@Tacosphere 

while in song view: hold an audio clip and turn select encoder to switch between three new audio clip types: player, sampler, looper

player has monitoring off
sampler and looper have monitoring on

sampler will turn off monitoring after you record to that audio clip
looper will always keep monitoring on and also enables you to use the new overdub audio recording for audio clips
