### ISSUE TITLE
Disabling 'Mod. Depth Decimals' on 7SEG doesn't disable the feature.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#326]
This seems to work as intended on OLED, however on 7SEG decimals still remain.

Bin I'm using is: deluge7SEG-v1.0.0-dev+2023.08.09-72926a5 (7SEG release)

**Comment by soymonitus** [comment]
@ok-reza could you re-test this with latest nightly?

**Comment by ok-reza** [comment]
confirming that latest nightly (deluge-v1_0_0-nightly+2023_09_05-593bfc5.bin) for 7SEG still shows decimals when Mod. Depth Decimals is set to OFF. (test by patch filter to env1, decimals show up)

**Comment by ok-reza** [comment]
@soymonitus i'm also noticing now that the osc1/osc2 transpose is missing it's decimal. if you change transpose to 1.00 it reads as '100'.

**Comment by ok-reza** [comment]
@bfredl is this something that you can address? still present in latest nightly for 7SEG
