### ISSUE TITLE
MIDI devices menu bug

### ISSUE THREAD

**Issue by trappar** [SynthstromAudible/DelugeFirmware#342]
After navigating to Settings -> MIDI -> Devices (with no devices connected) on my OLED deluge, I get a menu that appears empty, but with a weird little forward slash half way through the second line. If I attempt to scroll down nothing happens, but then if I attempt to scroll back up then what appears to be a left parenthesis appears before the forward slash.

I'm not sure what the normal behavior should be for this menu but I'm guessing it should say something like "No devices" instead of displaying random symbols.

**Comment by m-m-adams** [comment]
MIDI devices should show din even with nothing else connected

Definitely a bug but I don't think it's specific to that menu, I'm getting it semi randomly on screens in the global settings menu. Closing and reopening the menu seems to fix it

**Comment by m-m-adams** [comment]
MIDI devices should show din even with nothing else connected

Definitely a bug but I don't think it's specific to that menu, I'm getting it semi randomly on screens in the global settings menu. Closing and reopening the menu seems to fix it

**Comment by stellar-aria** [comment]
@trappar Could you verify that #344 fixes this issue and displays connected MIDI devices properly?

**Comment by trappar** [comment]
Yes it appears to fix this issue, but I'm still getting weird side effects that seem to be specifically associated with opening these menus. See this issue: https://github.com/SynthstromAudible/DelugeFirmware/issues/343

I can reproduced what's seen in the video from my latest comment there on a fresh boot on this firmware by doing nothing more than opening Settings -> MIDI -> Devices -> DIN Ports and scrolling around in there.
