### ISSUE TITLE
Cloning clip broken in latest nightly

### ISSUE THREAD

**Issue by trappar** [SynthstromAudible/DelugeFirmware#343]
On my OLED deluge, attempting to clone a clip yields a copy where the note positions are mangled.

[Here's a youtube video of what I'm seeing](https://youtu.be/N5y_0xC55Fc).

**Comment by PaulFreund** [comment]
Can you add a little more info how to get there? I was not able to reproduce with current HEAD or a build from yesterday coming from a clean state

**Comment by trappar** [comment]
The plot thickens...

This was with last night's nightly.

https://youtu.be/bGlSNReKvLA
