### ISSUE TITLE
Broken Refresh rate

### ISSUE THREAD

**Issue by moulfrit** [SynthstromAudible/DelugeFirmware#346]
Hello Dev’s

When you let clip press (in clip mode) and turn select, the refresh rate for the brightness of the leds no longer works. Ideally for the Oled  Deluge this one is around 120 to no longer see leds lit.
Thx

**Comment by bobtwinkles** [comment]
Reproduced, thanks for the report! The symptoms are the same as always setting the refresh rate to 0, and the deluge pops up a "0" indicated that this is the case.
