### ISSUE TITLE
Etablish guidelines and initial implementation for SYSEX messages

### ISSUE THREAD

**Issue by bfredl** [SynthstromAudible/DelugeFirmware#37]
Sysex messages allow midi devices to send arbitrary data in form of 7-bit messages. These take the following form:

```
F0 manufacturer_id_byte {arbitrary 0-127 byte values} F7
F0 00 manufacturer_id_1 manufacturer_id_2 {arbitrary 0-127 byte values} F7
```

manufacturer ids are normally allocated by the MIDI association, but there are ranges of ids which are "reserved" which can be freely used with some risk of collision.

Allow multiple sysex consumers
===

It will expected that various extensions to the community firmware will want to use sysexes for various purposes. Here I am using "extension" quite liberally, both for features which end up in the shared community branch and also for stuff people will work on and distribute in private forks (with no direct intention for merging)

I propose we set up some kind of standard for how sysex messages are prefixed, so the `MidiEninge` can "route" messages to the extension which can handle it and discard ones it doesn't know about.

Generally, a deluge-compatible sysEx (both sending and receiving) will have the following form.

```
F0 {deluge manufacturer prefix} {extension prefix} {arbitrary 7-bit data defined by the extension} F7
```

Thus incoming messages can be handled something like this
```c
// invoked by the serial and USB midi drivers after buffering
// a complete sysex message (and filter out high-prio system messages etc)
void handle_sysex_message(uint8_t *data, int len) {
    // data[0] is always F0
    if (data[1] != DELUGE_MANUFACTERER_ID) {
      // out of scope for this proposal, but would be possible
      // handle_foreign_sysex_msg(data, len)
      return;
    }

    int extension_id = data[2];
    switch (extension_id) {
        case 0: // transport control
            Song::handle_sysex(data, len); break;
        case 1: // transfer XML/WAV files over sysex etc
            storagemanager::handle_sysex(data, len); break;

        // these could come from merged branches from forks
        case 10:
            my_private_fetaure::handle_sysex(data, len); break

        ...

        default:
            // do nothing, print to log in debug mode?
    }
}

```
The final code will be more complicated as the deluge manufacturer id and the extension id could be longer than just one byte.

When sending messages, extensions will be expected to use the same prefix.

This assumes that individual messages cannot be streamed. extensions will only receive complete messages with a maximum, static size and are expected to break up long data transfers into many small sysex messages. This is what we want anyway to avoid head-of-line blocking of USB midi ports, so normal note messages can be sent interleaved

I've already experimented a bit with sysex handling, and a solution like this as part of `MidiEngine.cpp` should be approachable, but I am opening this issue to solicit feedback over a reasonable, forward-compatible design before working on a PR.

open questions
===
- [ ] pick a reasonable "manufacurer prefix" for the over all deluge device. Barring getting a standardized manufacturer id for synthstrom (unrealistic?), we need to pick a value in one of the ranges which are reserved for private use.
- [ ] determine reasonable lengths for the prefixes. with two bytes we will have 16384 unique ids.
- [ ] coordinate extension numbers for third-party extensions. this could could be a wiki page or something more organized

Convert 7-bit sysex data to 8-bit clean data
====
This is less of an immediate concern, but there is gonna be a need to send blocks of full 8-bit byte values.
There are standard solutions like this. Like sending the low 7-bits of a bunch of bytes then the highbits
collected to a single bytes (I've seen DSI/sequential synths doing this), which I used in my data transfer tests.
This could be exposed as utility functions so extensions won't need to reinvent this particular wheel.

**Comment by bfredl** [comment]
We need to consider how sysex interacts with multiple device support (related #12 ). The device id (and virtual cable/jack id) should be sent to the plugin if it cares about it (and reply to the same port). Likewise, an extensions might want to handle all sysex messages on a port for other manufacturer sysex:es (i e an extension to work with a particular synth and its own sysex:es)

**Comment by dctucker** [comment]
FWIW, I have a [lot](https://github.com/dctucker/roland-junods/blob/main/junods/src/memorymap.nim) of [experience](https://github.com/dctucker/roland-capture/blob/main/lib/mixer.c) with [Roland's SysEx](https://www.2writers.com/eddie/TutSysEx.htm) implementation. What I've seen in their messages is they'll typically have a fixed-length header that includes an instruction code (usually just "read" or "write") a parameter address, and finally parameter value. Depending on the instruction code, the number of bytes remaining in the message is often included.

It might make sense to always include the byte length in every message for ease-of-use.

SysEx with multiple devices is a little more tricky. Generally we'd want to ignore and forward messages lacking Deluge's manufacturer/device ID combo, and consume messages with no forwarding that do include them.

**Comment by designerfuzzi** [comment]
implement a NRPN (7/14bit/sysex) protocol for all available functions of the Deluge including addressing each of the 8x16 button matrix and watch what users can do with it. Basically this is how in example the ableton push2 works, each button has its address and color scheme coding via midi and the whole brain making it work is external (aka running in the DAW).

**Comment by drbourbon** [comment]
Not sure whether this is the proper thread, but here's a use case that SYSEX messages would enable: open support to external displays by doubling up every OLED call as outbound SYSEX message. This could include the 8x16 matrix write operations as well. Also, a request/response SYSEX sequence could be used to request full display / matrix to the deluge.
