### ISSUE TITLE
A song with just and audio clip, when loaded, has the clip button flashing

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#371]
@seangoodvibes found this accidentally but I think it's related to the Automation feature

**Comment by seangoodvibes** [comment]
Hrm it is possible this was my mistake. Can you confirm it doesn't flash with normal firmware?

Good catch

**Comment by soymonitus** [comment]
I think the deluge thinks wrongly that it is inside automation clip view. There must be a code path that leads to this behavior for audio clips

**Comment by seangoodvibes** [comment]
> I think the deluge thinks wrongly that it is inside automation clip view. There must be a code path that leads to this behavior for audio clips

Yea you're right there's a bug. Adding it to my list of things to fix.

Thanks!

**Comment by seangoodvibes** [comment]
@soymonitus This has been fixed. Can you test and close the issue if you are satisfied :)? Thx
