### ISSUE TITLE
Wave Folding param causes Error in Audio Clip

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#378]
@m-m-adams RE PR https://github.com/SynthstromAudible/DelugeFirmware/pull/349

I discovered a bug.

1. Create audio clip
2. Press Shift + Fold grid shortcut (pad to the left LPF frequency)
3. Deluge freezes with error "E411"

**Comment by m-m-adams** [comment]
I think this is related to the unpatched param stuff you told me about on Discord. The audio version of the menu should link to a seperate unpatched wavefold amount instead of the patched param

**Comment by seangoodvibes** [comment]
> I think this is related to the unpatched param stuff you told me about on Discord. The audio version of the menu should link to a seperate unpatched wavefold amount instead of the patched param

Makes sense! I had a feeling it was related to that discussion also.
