### ISSUE TITLE
Shift Audio Clip Feature Feedback

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#379]
@topisani RE PR https://github.com/SynthstromAudible/DelugeFirmware/pull/141

I think it's not working exactly the same as I would expect.

In the regular Instrument Clip View, when you rotate a clip, it wraps around e.g. if there's a note at 0,0 and you rotate left, that note appears on the other side of the grid (it's literally rotating the clip around).

I would expect the same with shifting/rotating an audio clip.  If you rotate an audio clip the beginning of the audio clip rotates around to the other end of the clip.

**Comment by sichtbeton** [comment]
He commented this somewhere: it would not work without larger code work for architectural reasons.
