### ISSUE TITLE
Visiting clip from grid mode can result in out of bounds clip page

### ISSUE THREAD

**Issue by trappar** [SynthstromAudible/DelugeFirmware#382]
When navigating to a clip from grid view (doesn't seem to apply to rows view), the clip will show the zoom level / page corresponding to the last viewed clip even if this is out of bounds for the current clip.

To reproduce:
1. Create clip longer than one measure.
2. Zoom and page to anywhere outside of the first measure.
3. Return to grid view.
4. Create a new clip.

You should see that the clip shows an entirely blurred page. Paging back to the in-bounds area works fine and once this is done you're locked into that section.

This is also reproducible without creating a new clip.

**Comment by PaulFreund** [comment]
Fixed in current release branch and nightly :) Please report if I overlooked anything
