### ISSUE TITLE
Note row probability: new inputed notes don't inherit the note Row probability set

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#385]
This one I guess is for @m-m-adams who developed the feature. When setting note row probability, that value is saved in the NoteRow, but it is only applied to existing notes. I would expect new inputed notes to have the same probability as the one set for the row, that is, inheriting the probability from the NoteRow object.

My assumption is that there must be somewhere in the code, which I don't know, some function that is called when a new note is added to a kit row, so we should take that opportunity to there get the NoteRow they belong to, and see if there is a probability set for that row, and if so, set it to the newly added note

**Comment by m-m-adams** [comment]
Hmm yeah that's a good idea. I'll think about how best to do it!
