### ISSUE TITLE
Can't adjust/remove the quantize/humanize value once entered

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#401]
RE: PR #129 by @alter-alter 

This is a fun feature with a lot of potential, so thanks for bringing it to the community! 

One issue I noticed is that once a value for humanize/quantize has been selected you can't go back later and adjust/remove it (instead, it seems to want to re-humanize/quantize the chosen clip even further). As such, the humanize/quantize value is permanently applied to the clip, which is unexpected and counter to most other Deluge parameters. 

It would be very useful to have this value be editable after the fact, so it can be adjusted as a song comes together, for instance.

**Comment by m-m-adams** [comment]
Decided this is handled by undo for now

Maybe this can be handled in the arp later instead but will be a complete rewrite
