### ISSUE TITLE
Selecting a clip in Grid mode deactivates quantized stutter

### ISSUE THREAD

**Issue by suivaht** [SynthstromAudible/DelugeFirmware#402]
In the latest build that includes quantized stutter (although it doesn't seem like this includes the automation pop-up fixes that were recently merged) I noticed that when I enabled quantized stutter in the runtime settings, went to the grid mode, turned on Affect All and then engaged stutter, if I keep holding the gold knob for the stutter effect when I select a clip on the grid the stutter effect immediately stops.  This behavior does not happen with the row layout (stutter stays engaged when selecting clips or sections).

**Comment by soymonitus** [comment]
I think this is a bug related to Grid mode feature, because when you engage a clip to play, the developer can decide if aborting the stutter going on or not.

**Comment by PaulFreund** [comment]
Fixed in current release branch and nightly :)
