### ISSUE TITLE
Load + Synth and Load + Kit doesn't work anymore. Also in Song mode, holding a row and changing instrument type makes Deluge freeze

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#403]
@m-m-adams This has to do with the new feature "Load synth preset to kit row" because by reverting it, the issue is gone. Do you think it is an easy fix to include it in the release? Or maybe that feature (which you stated is a bit hacky) needs more dev before going live?
Cheers!

**Comment by m-m-adams** [comment]
Both are only broken after using the load synth to kit row feature and I've found a fix for that, just a flag that needed to be explicitly set in the other places the preset browser is opened
