### ISSUE TITLE
Continuous overdub global midi command doesn't always overdub

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#407]
If the audio clip to be looped into is armed red then the continuous overdub command does not actually overdub. The loop command works as expected regardless of the armed clip colour.

Fix: change that when the overdub midi command is received

**Comment by soymonitus** [comment]
Please close tis as it is fixed by mentioned PR

**Comment by m-m-adams** [comment]
Thanks, I keep forgetting that auto code isn't working
