### ISSUE TITLE
Fill iteration mode cannot be set for notes which have been configured with Note Repeat

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#412]
When you hold a note and press and turn the up/down knob you increase the number of Note repeats of that note. If you also hold it and turn the Select knob you change the iteration mode for all the repetitions of that step. The bug is that the probability iterations you can select only reach 5%, they don't go down till the Fill condition
@weavermedia

**Comment by weavermedia** [comment]
Sorry, I don't have time to look at this right now. Happy for anyone else to jump in.

**Comment by m-m-adams** [comment]
Can you check if this is now fixed? I wasn't specifically looking at it but might have gotten it anyway

**Comment by soymonitus** [comment]
@m-m-adams this is fixed here:

https://github.com/SynthstromAudible/DelugeFirmware/pull/476
