### ISSUE TITLE
Turning < > while holding clip pad on grid view bug

### ISSUE THREAD

**Issue by mcabrerapf** [SynthstromAudible/DelugeFirmware#413]
When in grid mode, while holding a clip pad and turning the < > encoder, the view will remain stuck in a semi clip view where you can move the gold encoders.

**Comment by m-m-adams** [comment]
Can you confirm exactly what version you built? This was broken in the release branch from about midnight last night to noon today but should be fixed now. The community branch and nightly release shouldn't have had the issue

**Comment by mcabrerapf** [comment]
Im on nightly version `deluge-v1_0_0-nightly+2023_08_23-af2538b`
Heres a video showing the issue


https://github.com/SynthstromAudible/DelugeFirmware/assets/21365117/ba8a3cde-30d4-477f-a917-4ae0d0937b76

**Comment by seangoodvibes** [comment]
@PaulFreund FYI

**Comment by PaulFreund** [comment]
Fixed in current release branch and nightly :)
