### ISSUE TITLE
CV OUT1 and OUT2 text displaying strangely on 7SEG

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#425]
Depending on the unit, either OUT1 or OUT2 does not seem to be displaying consistently in the CV menu on 7SEG (for me, OUT1 is blank while OUT2 displays fine, though @m-m-adams reports the opposite on his unit). 

Steps to reproduce: 

- SHIFT + Push the Select knob to enter the global menu
- Navigate to "CV" and press the select knob
- Either OUT1 or OUT2 may now be blank (you can still click the select knob to access the sub-menu parameters though)

**Comment by stellar-aria** [comment]
I'm no longer able to replicate this. @m-m-adams you fixed this in #465 right?

**Comment by m-m-adams** [comment]
Yeah should be fixed
