### ISSUE TITLE
MIDI Takeover Pickup hanging

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#427]
**Describe the Issue**
If Pickup is selected for MIDI takeover mode the values from my external encoder is only picked up if changed very slowly and otherwise hangs. 
Might originate in #170

**Expected Behavior**

I expect the value to not change until the current value is met and then always change

**Deluge Version**

OLED

**Firmware Version**

Built from release/1.0

_Firmware Version in the file name or display:_ d3171ebd549abb220505a5f74cf5235658075743

_Steps to Reproduce the Issue_

1. Enable MIDI takeover mode in MIDI settings
2. Open Clip and open value like Pan or OSC1 PW
3. Hold learn and turn knob
4. Turn the knob very fast over the current value and see that it only changes once
5. Turn very slowly to see it change continusoly

**Comment by PaulFreund** [comment]
@seangoodvibes FYI

**Comment by soymonitus** [comment]
This was fixed yesterday in referenced PR. Please close
