### ISSUE TITLE
Adding notes with fill mode on does not create fill notes

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#451]
### Please describe the problem:

notes added while fill is held are not fill notes

### What is the expected behavior?

When adding notes while holding fill they should be created as fill notes

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from release/1.0

**Comment by seangoodvibes** [comment]
Adding to this:

Added euclidean notes with fill mode on does not create fill notes.
