### ISSUE TITLE
Tracks missing contents in old songs

### ISSUE THREAD

**Issue by Icoustic** [SynthstromAudible/DelugeFirmware#462]
### Please describe the problem:

After loading a couple of old songs and playing back i.e. streaming audio files from SD, upon loading another, screen says "SD card error" then the song loads with tracks present but missing contents i.e. no files or colors in clips (when attempting to replicate, problem does not seem to arise when several old songs are loaded without actually playing inbetween). These are large songs with plenty of tracks and samples used.
Issue doesn't happen with a specific song every time, it happens after loading (and playing?) a certain amount of the songs consecutively.
Not having same issue with previous non-community official firmware, on same SD card.

Relevant info: Big SD card, 400GB

I can provide collect media save(s) for some songs if needed

### What is the expected behavior?

Old songs should load like they're supposed to

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

d56dfaa

### If possible provide the steps to reproduce the issue and upload additional media:

1. Power on 
2. Load song 1 in given setlist, play a few secs 
3. Load song 2 in setlist, play a few secs
4. Load song 3 in setlist, screen says "SD card error", song loads with missing contents

**Comment by m-m-adams** [comment]
I can't reproduce this - it would be great if you could share some of the songs with issues

**Comment by Icoustic** [comment]
> I can't reproduce this - it would be great if you could share some of the songs with issues

Sure, here's a wetransfer link to 3 songs which should be enough to replicate the issue. The issue can happen with any of the songs, depending on what order they are opened and played in.

I'm guessing this is some memory leak thing becoming apparent due to the songs being big and packed.

https://we.tl/t-h0jjB4pATW

**Comment by m-m-adams** [comment]
Likely related to #350 and #491

**Comment by Icoustic** [comment]
> Likely related to #350 and #491

Seems like it!

**Comment by PaulFreund** [comment]
Can you please retest with tomorrows nightly (probably generated in ~2h)?

**Comment by Icoustic** [comment]
> Can you please retest with tomorrows nightly (probably generated in ~2h)?

Sure 🙂

**Comment by Icoustic** [comment]
> Can you please retest with tomorrows nightly (probably generated in ~2h)?

Yep, its working now. The track I linked in #491 plays like it should/does on the official firmware, and I’m no longer getting the SD card errors 👍

**Comment by Icoustic** [comment]
Ok hold on I am still getting the SD card errors but it takes longer i.e. loading and playing more songs. Before, I’d consistently get it after loading 3 songs, but now its like 7.

**Comment by PaulFreund** [comment]
Okay it seems like your error is dependent on how much memory is available, that is a good clue! Can you try testing the same with official and push it with loading more?

**Comment by Icoustic** [comment]
> Okay it seems like your error is dependent on how much memory is available, that is a good clue! Can you try testing the same with official and push it with loading more?

Yeah, did that, SD errors dont happen with official it seems. I’m guessing it clears out memory somehow between songs; on nightly, the error only becomes apparent with large and sample heavy songs, particularly with many audio clips, and I presume it stacks up and overloads

**Comment by Icoustic** [comment]
> > Can you please retest with tomorrows nightly (probably generated in ~2h)?
> 
> Yep, its working now. The track I linked in #491 plays like it should/does on the official firmware, and I’m no longer getting the SD card errors 👍

Dropout issues are back, audio clip stops playing mid-sequence, and all audio clips are subsequently broken (won’t play all the way thru even though they did previously before the longest loop dropped out) and don’t return to normal until reboot

**Comment by m-m-adams** [comment]
What firmware version string?

**Comment by Icoustic** [comment]
> What firmware version string?

The nightly from the 9th that remained for a few days

**Comment by m-m-adams** [comment]
yeah try again now, there was extra logging enabled that impacted performance

**Comment by Icoustic** [comment]
> Ok hold on I am still getting the SD card errors but it takes longer i.e. loading and playing more songs. Before, I’d consistently get it after loading 3 songs, but now its like 7.

@PaulFreund FYI, this issue has gotten worse again, current beta. Happens after 3ish songs now (SD card error during loading, audio clip contents missing)

**Comment by Icoustic** [comment]
As mentioned in #491 , still seeing these issues @m-m-adams

**Comment by m-m-adams** [comment]
The current memory issues are being tracked in #643, we're aware of the underlying issue just not sure how best to fix it
