### ISSUE TITLE
Saving settings to SD card can silently fail if card is in RO mode

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#471]
### Please describe the problem:

When writing out settings (MIDI device config, community features) the save will silently fail if the SD card is in RO mode.

### What is the expected behavior?

A warning should be presented indicating that saving settings didn't work. 

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

nightly, community, Built from community, Built from release/1.0

### What is the firmware name:

dbaa84209d7edf7079366871e8933a98635805d1

**Comment by M0R172** [comment]
This should be closed, I guess.

**Comment by sapphire-arches** [comment]
Fixed by #1001
