### ISSUE TITLE
Loop on waveform view not working 

### ISSUE THREAD

**Issue by moulfrit** [SynthstromAudible/DelugeFirmware#472]
### Please describe the problem:

In waveform view loop shortcut ( green / red bar + any pad ) doesn’t not working .

### What is the expected behavior?

Make loop section

### Is there a relevant Pull request?

I don’t know 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

Deluge-v1_0_0-nightly+2023_08_29-dbaa842.bin

### If possible provide the steps to reproduce the issue and upload additional media:

1.open waveform view

2.press green bar+ any pad

result: nothing is happens

**Comment by m-m-adams** [comment]
I'm troubleshooting a bit and if you zoom in far enough that the loop point and the start point no longer overlap you can move them around properly. Looks like the bug might be that there's a loop point by default for some reason

**Comment by stellar-aria** [comment]
Closing as fixed by #619
