### ISSUE TITLE
Gate out triggers when note is released not when initially pressed

### ISSUE THREAD

**Issue by pssssssst** [SynthstromAudible/DelugeFirmware#473]
### Please describe the problem:

The gate outs send a trigger when releasing a key, not when pressing it.
This happens using the sequencer as well as the audition pads and also when playing notes on a midi keyboard.
Switching the gates to s-trig makes them behave like the should if they where v-trig gates.
So it is as if s-trig and v-trig were switched.
I also checked with the official firmware, where it still works correctly.

### What is the expected behavior?

v-trig Gates should be triggered (high) when note is pressed and grounded when note is released.
s-Trig  vice versa

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

25ABE47

**Comment by m-m-adams** [comment]
Probably a menu bug if switching them works properly
