### ISSUE TITLE
Performance issues with noticable sample cutout

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#491]
### Please describe the problem:

Performance seems to be degraded which is especially noticable for sample heavy tracks since sample cutout is very noticable.

Reproduction is  done with this song: [CORDAE](https://discord.com/channels/608916579421257728/991432258286268496/1146194461626474600)

### What is the expected behavior?

The song can be played in full without cutouts with current Official Beta and e2 generated v4.1.4-alpha3 commit. 

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly, community, Built from community, Built from release/1.0, other

### If possible provide the steps to reproduce the issue and upload additional media:

1. Copy https://discord.com/channels/608916579421257728/991432258286268496 to your Songs folder
2. Load either firmware with Load/Run OLED Release
3. Load song (CORDAE) - Arranger is opening
4. Play the song and listen, tracks are indexed from 1 top to bottom
    * Latest Rohan beta/release or 4.1.4-alpha3 with e2: All tracks play to the end without manual interaction with the device
    * fa9ab593: It is normal that track 3 (rap acapella) is cutting out 8/10 times all other sounds should continue to play through
    * 5f80c5c4: 
        * track 3 (acapella) is cutting out between pad 5 to 7 from the left
        * track 5 (bass) is cutting out at some point
        * track 6 (bells) is cutting out shortly after starting every time
        * track 7 (pad) can also cutout

**Comment by PaulFreund** [comment]
There seem to be three known sources of decreased performance currently:
1. #350 seems to be happening once internal memory allocation for objects in the audio path fails and they are moved to SDRAM
2. From Scons (fa9ab59) to CMake (5f80c5c) there seems to be a quite big delta
3. From e2 (GCC9) to dbt (GCC10/12) there seems to have been a smaller but noticable delta too 

Better performance tracing will be of great use to get back or exceed preexisting performance

**Comment by Icoustic** [comment]
Seeing the same when comparing with official beta on elaborate songs with lots of audio clips/ samples

**Comment by m-m-adams** [comment]
Should we close this out or find a new reference song? Cordae no longer cuts out in nightly builds

**Comment by stirman** [comment]
Confirmed. I can't reproduce this issue with the latest nightly build as of today. Thx devs!!! <3

**Comment by Icoustic** [comment]
> Should we close this out or find a new reference song? Cordae no longer cuts out in nightly builds

I can reproduce with this song of mine; plays normal on official beta, while in nightly build (11/9) audio clip loop cuts out.
Specifically, the bottom audio clip bassline (playing in the provided project), which is 64 bars long. On nightly build, it always cuts out at bar 62ish.
Starts playing again on the next 1, but is now "stunted" and can't even play as long as before, and keeps cutting out.

Link coming up

**Comment by PaulFreund** [comment]
Fixed with #541

**Comment by Icoustic** [comment]
> > Should we close this out or find a new reference song? Cordae no longer cuts out in nightly builds
> 
> I can reproduce with this song of mine; plays normal on official beta, while in nightly build (11/9) audio clip loop cuts out. Specifically, the bottom audio clip bassline (playing in the provided project), which is 64 bars long. On nightly build, it always cuts out at bar 62ish. Starts playing again on the next 1, but is now "stunted" and can't even play as long as before, and keeps cutting out.
> 


This issue is back again now, current nightly.

**Comment by PaulFreund** [comment]
Please test again with the new nightly, the last one had audio logging on by accident. Optimally test with current beta now since we work on getting that as stable as possible.

**Comment by stirman** [comment]
I haven't been able to duplicate this issue with any nightly builds in the
last month or so.

—
Stirman
https://instagram.com/stirman

**Comment by Icoustic** [comment]
> Please test again with the new nightly, the last one had audio logging on by accident. Optimally test with current beta now since we work on getting that as stable as possible.

Tested beta, yeah, back to the way it was now :)

**Comment by stirman** [comment]
Sorry, was traveling. Back now, tested on today's nightly build, can't reproduce the issue with long samples. Can't reproduce the issue with the original "Cordae" track either.

**Comment by Icoustic** [comment]
> > > Should we close this out or find a new reference song? Cordae no longer cuts out in nightly builds
> > 
> > 
> > I can reproduce with this song of mine; plays normal on official beta, while in nightly build (11/9) audio clip loop cuts out. Specifically, the bottom audio clip bassline (playing in the provided project), which is 64 bars long. On nightly build, it always cuts out at bar 62ish. Starts playing again on the next 1, but is now "stunted" and can't even play as long as before, and keeps cutting out.
> 
> This issue is back again now, current nightly.

I still see this issue with long audio clip dropping out and song subsequently getting messed up all around and dropping more voices @PaulFreund @m-m-adams 
Beta from 27th.

**Comment by Icoustic** [comment]
And also the SD card error from #462 still happening, unlike official rel/ beta where it never happens as such

**Comment by stirman** [comment]
Seeing this issue again, and it's cutting off much shorter samples now. Let me know if there's something specific I can help test. On nightly build from about a week ago.

**Comment by PaulFreund** [comment]
:) Hey @stirman my general recommendation is to always test with the newest release before reporting as sometimes there can be intermittent issue. if you test now you will get a build without known issues like that. The only situation where I could get your song to drop out was when I completely filled the audio cache with multisample mashing before and then only one playthrough, the ones after that worked fine.

**Comment by stirman** [comment]
Totally, I know better. I got today's build (2023_11_03-337c437) and I can't reproduce the issue again. Will continue trying with more songs/samples and report back if I can repro this issue. Thx again for all the work you community devs do, it's amazing!

**Comment by Icoustic** [comment]
> > > > Should we close this out or find a new reference song? Cordae no longer cuts out in nightly builds
> > > 
> > > 
> > > I can reproduce with this song of mine; plays normal on official beta, while in nightly build (11/9) audio clip loop cuts out. Specifically, the bottom audio clip bassline (playing in the provided project), which is 64 bars long. On nightly build, it always cuts out at bar 62ish. Starts playing again on the next 1, but is now "stunted" and can't even play as long as before, and keeps cutting out.
> > 
> > 
> > This issue is back again now, current nightly.
> 
> I still see this issue with long audio clip dropping out and song subsequently getting messed up all around and dropping more voices @PaulFreund @m-m-adams Beta from 27th. Got it on video if needed

Just letting you know I can still reproduce the issue I mentioned in quote above, on latest beta downloaded last night.
Can't play 64 bar audio clip loop all the way thru, breaks other voices after.

**Comment by m-m-adams** [comment]
Can you share the song? I want to look at exactly why it's dropping the voice

**Comment by Icoustic** [comment]
> Can you share the song? I want to look at exactly why it's dropping the voice

Sure, will send in a few hours

**Comment by Icoustic** [comment]
> Can you share the song? I want to look at exactly why it's dropping the voice

Here’s the song again, the long audio clip is the one with pink section color. Drops out after some time and then other clips are also affected. As mentioned before this all plays fine on the latest official Synthstrom release and 4.1.4 beta.

https://we.tl/t-s5xN1SBclm

**Comment by m-m-adams** [comment]
I don't know if I'm playing it wrong but I'm playing the pink section and it's played through 4 times without dropping any voices so far. Are you sure you're on the latest beta and the update took effect?

**Comment by m-m-adams** [comment]
Even after loading and playing other songs this song continues to play fine for me. Please let me know if there's something else that I need to do beyond playing the pink section

**Comment by Icoustic** [comment]
> Even after loading and playing other songs this song continues to play fine for me. Please let me know if there's something else that I need to do beyond playing the pink section

Really? Is the pink one the one with 64 bars or did I mix it up? Did you play it together with other tracks?
I can reproduce it easily. Could it have somehting to do with using a larger SD card? I use 400GB. But as mentioned it plays fine on official firmware.

**Comment by Icoustic** [comment]
> I don't know if I'm playing it wrong but I'm playing the pink section and it's played through 4 times without dropping any voices so far. Are you sure you're on the latest beta and the update took effect?
> 
> Cool song!

I was on the beta before yesterday's latest when I wrote it - wouldn't think it'd be fixed inbetween, but I need to double check in studio later if the latest is different.

**Comment by Icoustic** [comment]
> Even after loading and playing other songs this song continues to play fine for me. Please let me know if there's something else that I need to do beyond playing the pink section

Well, good news, it is indeed working *most* of the time, but by loading a couple more sample heavy and close-to-the-ceiling songs (3-4 ish), it does happen. Tried reverting to beta from nov7, reproduced there couple of times with loading more stuff as mentioned. On beta from nov10, same thing, maybe a bit better, kinda hard to tell as the bug is a bit obscure, sneaky and sporadic. The type I hate 😂😭


I’m having a hard time reproducing those old SD card errors though at least, so that’s a good thing 🙂

**Comment by m-m-adams** [comment]
Definitely this song would have had issues before the 2nd but I don't think anything would have changed since then. It's possibly very close to failing to play properly so that minor random differences in the memory layout lead to issues.

We have a few more optimizations for memory use in mind so hopefully they can get it working repeatedly!

**Comment by Icoustic** [comment]
> Definitely this song would have had issues before the 2nd but I don't think anything would have changed since then. It's possibly very close to failing to play properly so that minor random differences in the memory layout lead to issues.
> 
> We have a few more optimizations for memory use in mind so hopefully they can get it working repeatedly!

Cool 👍 If needed (if you weren't able to reproduce), I can send a couple heavy songs so you can check it

**Comment by m-m-adams** [comment]
Can you try this PR? https://github.com/SynthstromAudible/DelugeFirmware/pull/716 

The current build is here - https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/6843170006

**Comment by Icoustic** [comment]
> Can you try this PR? #716
> 
> The current build is here - https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/6843170006

Sure, ASAP!

**Comment by Icoustic** [comment]
> Can you try this PR? #716
> 
> The current build is here - https://github.com/SynthstromAudible/DelugeFirmware/actions/runs/6843170006

Issue still there 😕 Load and play some big songs, come back to the one I sent here, and most voices drop quickly from the start while the 64 bar audio clip isn’t even playing yet.
It just seems to stack up stuff in memory from past songs when loading new ones and doesn’t clear it out fast enough. Not that I know, I’m no coder. After restarting playback several times things seem to start playing right again, but that’s not exactly ideal behaviour

**Comment by m-m-adams** [comment]
Would you mind checking the cluster size on your SD card?

**Comment by Icoustic** [comment]
> Would you mind checking the cluster size on your SD card?

I'm not by my Deluge(s) now I'm pretty sure its 32kb, on my 400gb card. Will confirm later

**Comment by PaulFreund** [comment]
@Icoustic If you want to test immediately you can try this build https://github.com/SynthstromAudible/DelugeFirmware/suites/18180188491/artifacts/1049081351 otherwise I can notify you once the PR is merged :)

**Comment by Icoustic** [comment]
> @Icoustic If you want to test immediately you can try this build https://github.com/SynthstromAudible/DelugeFirmware/suites/18180188491/artifacts/1049081351 otherwise I can notify you once the PR is merged :) Should hopefully fix all the remaining dropouts

Checking it out now 👍

**Comment by PaulFreund** [comment]
@Icoustic would be great to get an update :) Eagerly hoping for confirmation

**Comment by Icoustic** [comment]
> @Icoustic would be great to get an update :) Eagerly hoping for confirmation

Hey, sorry for the wait & suspense! Been super busy and haven't had any time, but I'm going to test properly tonight and I'll report back

**Comment by Icoustic** [comment]
@PaulFreund It seems to be good now! 👍👍 No irregular voice drops, and no “SD card error”s! Big ups 🥇 and thanks

**Comment by PaulFreund** [comment]
Thank you so much for the feedback :) closing again for now!
