### ISSUE TITLE
Song previews display inverted when loading a new song.

### ISSUE THREAD

**Issue by 0beron** [SynthstromAudible/DelugeFirmware#503]
### Please describe the problem:

Once a song is loaded, pressing [LOAD] once more goes back to the song browser, however the preview image on the pads for the current song is displayed upside down. Navigating away and back to the same song then displays it in the original orientation.

### What is the expected behavior?

Song preview orientation should be consistently oriented whenever shown in the song browser.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from release/1.0

### What is the firmware name:

4c0bf781877e905d8b96e628d75baf4d30a33682

### If possible provide the steps to reproduce the issue and upload additional media:

1. Load any song (well, one with a preview image where you can tell if it's inverted or not!). Pads match the preview image since it is freshly loaded.
2. Press [LOAD] to return to the song browser. Pads dim and show the preview image again, but observe it is inverted.
3. Turn [SEL] to navigate one song left or right, and back again, image is now right-side-up.

**Comment by ok-reza** [comment]
confirmed on my end too, the animation is also inverted vertically.

**Comment by stellar-aria** [comment]
Fixed with #551
