### ISSUE TITLE
MIDI Learn on kit tracks not working

### ISSUE THREAD

**Issue by trappar** [SynthstromAudible/DelugeFirmware#506]
### Please describe the problem:

On my deluge, if I try to learn midi on synth track, everything works as expected, but when I try to do the same thing on a kit track, the UI shows that I've successfully mapped a row to a specific note, but then will not play when I trigger that note.

This happens for me uniformly on both DIN and USB inputs.

I asked about this in the nightly-testing channel. @ok-reza and @m-m-adams tested this and @ok-reza saw the same behavior I'm seeing while @m-m-adams was not able to reproduce the issue. We all installed the same version of the firmware on our devices and it didn't change anything. We also went through all of the settings in the MIDI menu and some other settings to see if it might be influenced by a setting stored in flash, but we weren't able to identify any differences between our devices' settings.

### What is the expected behavior?

I should be able to hold `Learn` + `Audition` in a kit and then trigger a note on a MIDI device to map that kit row to that note (this works).

Then I should be able to trigger that same MIDI note and have the kit row be triggered.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly, community, Built from release/1.0

**Comment by ok-reza** [comment]
I can successfully make this work if the midi channel of the external device is set to 2-15, channels 1 & 16 cause the issue.
