### ISSUE TITLE
Change Automation Community Features settings to defaults

### ISSUE THREAD

**Issue by seangoodvibes** [SynthstromAudible/DelugeFirmware#530]
### Please describe the problem:

Per guidance from @m-m-adams:

- [ ] Move automation community features menu to Defaults/UI/Automation menu

### What is the expected behavior?

No community features menu required for automation view

Make use of defaults menu where possible

### Is there a relevant Pull request?

https://github.com/SynthstromAudible/DelugeFirmware/pull/241

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from release/1.0

**Comment by seangoodvibes** [comment]
@m-m-adams based on the question we got on discord today, I think we need to re-consider the following proposed change:

- Make Clear Clip/Shift Clip/Nudge Note automation changes permanent for Instrument Clip

I think some users will want to adjust automation together with their notes. E.g. the user today asked how to shift/nudge automation together with their notes.

Should we just move all the automation view community features settings to defaults?

**Comment by m-m-adams** [comment]
Yeah maybe it should be a 'link' option, where shifting automation shifts notes and vice versa
