### ISSUE TITLE
Inconsistency in the display name for the stereo chorus effect on 7SEG units

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#532]
### Please describe the problem:

On a 7SEG unit, when selecting the stereo chorus effect via the TYPE shortcut the display reads "S.CHo". However, when selecting stereo chorus by pressing the gold knob, it reads "StER". 

### What is the expected behavior?

Stereo chorus should be labelled the same in both cases (doesn't matter which, as long as they are consistent)

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

deluge-v1_0_0-nightly+2023_09_09-799dc8b

**Comment by stellar-aria** [comment]
Fixed with #553
