### ISSUE TITLE
Firmware menu renamed to "VER." on 7SEG units, which may confuse users as it contradicts the manual

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#535]
### Please describe the problem:

On 7SEG units, when navigating the global menu (SHIFT + Select knob) the firmware section now reads "VER." instead of "FIRM". This contradicts the official manual and may cause confusion for users. 

### What is the expected behavior?

The global menu entry to view the firmware option on 7SEG units should read "FIRM" 

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

deluge-v1_0_0-nightly+2023_09_11-4702342

**Comment by bobtwinkles** [comment]
Fixed in release, closing.
