### ISSUE TITLE
Monitoring external audio gets muted if parameters have been edited and the clip is not in launched state in song view

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#558]
### Please describe the problem:

Editing parameters (pan, freq, fx, etc.) of an audio clip causes the monitored audio to be muted unless the audio clip is in a launched state (green) in song view.

(No tracks are muted in arranger view in this scenario)

### What is the expected behavior?

If monitoring audio has been selected (dot beside the audio source on 7SEG) the incoming audio should be heard regardless of the audio clips launch status in song view (red or green), as per existing behaviour. 

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

deluge-v1_0_0-nightly+2023_09_19-e3d5956

### If possible provide the steps to reproduce the issue and upload additional media:

- Connect an external device/audio source to the line input
- Create a new audio track and set it to monitor the line input (a "dot" beside the selection on 7SEG)
- Play the external sound source (should play fine)
- In song view, un-launch the clip by tapping the mute/launch button, which will turn red (should still play fine)
- open the audio clip and adjust one of the gold knobs (volume seems unaffected, but try pan or freq) 
- The audio will suddenly mute
- In song view, launch the audio clip, turning the mute/launch button green and the audio will un-mute

**Comment by m-m-adams** [comment]
Reproduced - seems to depend on how far you adjust knobs as well
