### ISSUE TITLE
Freeze of OLED screen and all pads that are connected to the PIC

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#564]
### Please describe the problem:

After some runtime (depending on situation) the interrupts for 

DMA_INTERRUPT_0 + 10 (PIC_TX_DMA_CHANNEL)
DMA_INTERRUPT_0 + 11 (MIDI_TX_INT_TrnEnd)

are no longer fired, severing all interaction with OLED and pads. At least for me for some time I could still start and stop playing

### What is the expected behavior?

This does not happen

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly, Built from release/1.0, other

### What is the firmware name:

Traced back to at least e3d595693595c615cb01f1fd06e424fc240f79b8

### If possible provide the steps to reproduce the issue and upload additional media:

1. Load a song (relevant parameters unknown)
2. Open clip view of a playing clip to see playhead scrolling through
3. Set tempo to FAST (max)
4. Wait for a random amount of time (shortest for me was 1 min, highest was >1hour without happening)

Happens in debug and release, in debug you can see that the interrupts above are no longer called

**Comment by PaulFreund** [comment]
[Hangtest2.zip](https://github.com/SynthstromAudible/DelugeFirmware/files/12706773/Hangtest2.zip)

This is basically the song I replicated with but with a different kit because of sample origin

**Comment by stellar-aria** [comment]
Tentatively closing  as fixed by #611, if we find this is still present the issue can be reopened.
