### ISSUE TITLE
Kit clip audition and keyboard pads do not sound if clip is muted in song view.

### ISSUE THREAD

**Issue by 0beron** [SynthstromAudible/DelugeFirmware#575]
### Please describe the problem:

Muting (red status pad) a kit clip in song view results in the audition pads and drum keyboard pads no longer sounding when in clip view / keyboard view.

### What is the expected behavior?

The audition pads / drum keyboard should sound regardless of clip mute status.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

78888ef0ec1f17eb655f3ea3a436e0b8f0a26421

### If possible provide the steps to reproduce the issue and upload additional media:

1. New Song
2. Make a new kit clip and a synth clip.
3. Ensure both are unmuted in song view.
4. Enter clip view and play audition pads - both clips sound.
5. Mute both in song view
6. Play audition pads in clip view - observe the kit is silent but the synth plays. Also applies to the respective keyboard views.

**Comment by stellar-aria** [comment]
Fixed by #576
