### ISSUE TITLE
ODR violations

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#580]
### Please describe the problem:

There are piles of ODR violations since merging #567 

### What is the expected behavior?

Not having them

### Is there a relevant Pull request?

#567

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Built from community, Built from release/1.0

**Comment by duncanrmi** [comment]
what is ODR?

**Comment by bobtwinkles** [comment]
ODR is the [one definition rule](https://en.cppreference.com/w/cpp/language/definition). This bug is for some internal/technical problem, we haven't observed any user-visible problems associated with this (yet..)
