### ISSUE TITLE
Deluge freezes trying to assign midi controller to grain feedback on audio track with monitoring

### ISSUE THREAD

**Issue by pssssssst** [SynthstromAudible/DelugeFirmware#587]
### Please describe the problem:

When i try to assign an external midi controller to grain feedback or offset on a monitored audio track the deluge freezes.
This happens only when monitoring is on. 
Assigning with monitoring off works just fine. I can also turn on monitoring after the controller is assigned and everything works as expected.

### What is the expected behavior?

no freezes :)

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

1.0.0-beta-D9FBDE6

### If possible provide the steps to reproduce the issue and upload additional media:

1. New track
2. change clip to audio track
3. select "stereo in (monitored)" or any other monitored audio source
4. change "mod fx type" to "grain"
5. select "feedback" or "offset" (sometimes the other ones freeze as well)
6. hit "learn/input" and turn your external midi controller
7. freeze

**Comment by m-m-adams** [comment]
Happens on c56cdb5b but not 69d40321 so probably my fault
