### ISSUE TITLE
Stale version string in local builds

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#591]
### Please describe the problem:

Version strings from the same local build are stale if the build directory is not deleted (or CMake used to manually re-run the configure step).

### What is the expected behavior?

https://github.com/SynthstromAudible/DelugeFirmware/blob/f3b2407134d76a811a0f01b8e7c15d28b1792f90/src/deluge/CMakeLists.txt#L1 should use https://cmake.org/cmake/help/latest/command/file.html#generate instead, so it reruns on every *build* not every *configure*.

### Is there a relevant Pull request?

N/A

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

nightly, community, Built from community, Built from release/1.0

**Comment by stellar-aria** [comment]
Generate doesn't do variable replacement, as far as I'm aware

**Comment by m-m-adams** [comment]
Maybe we could have dbt build release always run the configure step?

**Comment by m-m-adams** [comment]
What if we just make a commithash.h file and set the content with dbt or git hooks?
