### ISSUE TITLE
Synth sounds sound different (suspected Osc Sync problem)

### ISSUE THREAD

**Issue by 0beron** [SynthstromAudible/DelugeFirmware#592]
### Please describe the problem:

Synth sounds in existing songs, and some presets sound different.
It's most audible in preset number 1, (where rich saw bass is 0) - the effect of LFO1 modulating osc 2 transpose is much less noticeable, and when triggering repeated notes, occasionally you get a metallic hiss.

Bisected back to commit 51c9195 where the problem first seems to occur.

### What is the expected behavior?

Presets and synth sounds without use of community features should sound the same as in official.

### Is there a relevant Pull request?

#550

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

51c91955949749e0e72854b710a92e4cc6d21349

### If possible provide the steps to reproduce the issue and upload additional media:

Start a new song and turn the select dial one click to preset 1. Play repeated notes on the audition pads, about 1 in every 10 notes has the metallic sound.

**Comment by m-m-adams** [comment]
Labeling as future since this isn’t present in release branch
