### ISSUE TITLE
Modfx parameter got modulated at the same time as the filter cutoff

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#593]
### Please describe the problem:

Some modfx parameter was tied to a LFO while I was adjusting the LFO amount for the filter cutoff. I was adding some S&H modulation to the filter cutoff from a fresh new synth (Shift + Synth). Then i went to change modfx type (selecting Stereo chorus) and the sound was super weird, as if the rate of the stereo chorus was modulated also by the S&H lfo. It became more evident when changed Stereo chorus to Flanger that the parameter that got tied to the LFO1 was Rate, as later I tried with a new sound to manually do the same at it sounded exactly like that. Don't know if there will be a bug or not but maybe someone can check if there is some code path that will allow several parameters to be modulated at the same time.

### What is the expected behavior?

If I add modulation for the filter cutoff, only the filter cutoff is modulated and not other parameters at the same time

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

deluge-v1_0_0-beta+2023_10_02-d9fbde6

### If possible provide the steps to reproduce the issue and upload additional media:

Not able to reproduce now

**Comment by m-m-adams** [comment]
Confirmed, some mod routings seem to go to the wrong spot. Modulating env 2 modulates env 1, modulating vibrato modulates transpose, osc 2 hits osc 1 and probably more

**Comment by soymonitus** [comment]
From your description it seems they are  all just one position off, like someone introduced a new element in an array and forgot to increase the indexing

**Comment by soymonitus** [comment]
I was going to pick this bug to fix it but can't reproduce it now. Was this fixed as part of another PR?

**Comment by m-m-adams** [comment]
I've still got it showing up when modulating osc 2, mod 2 and env 2
