### ISSUE TITLE
"OFF" LFO1 Sync option unavailable in FM & RING Synth Modes

### ISSUE THREAD

**Issue by LuminOne** [SynthstromAudible/DelugeFirmware#613]
### Please describe the problem:

When utilizing these modes and choosing to sync the LFO1 to any parameter, initially OFF is an option, but when selecting a division (1 bar, 8th, 16th etc), OFF is no longer available. The options just repeat. 
To be able to select OFF again, I had to select any another parameter and then return to the LFO Sync Menu to then find OFF.

I found this only with FM & RING modes. Subtractive is fine (at least in my testing).

### What is the expected behavior?

That OFF would be in the sync menu for these modes.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

community

### What is the firmware name:

deluge-v1_0_0-beta+2023_10_02-d9fbde6

**Comment by m-m-adams** [comment]
I can't reproduce this, I still have off in the sync menu on FM and ring mod synths. If you can take a video or provide more detailed reproduction instructions please reopen the issue
