### ISSUE TITLE
MIDI CCs learning don’t work correctly in old songs

### ISSUE THREAD

**Issue by Icoustic** [SynthstromAudible/DelugeFirmware#615]
### Please describe the problem:

MIDI CCs don’t work correctly for audio clips and synth clips in old songs. 
Learning happens but the CCs don’t change the parameter. (In kits it works normally.)
Have to re-save old song with current new firmware, then the CCs work as expected.

### What is the expected behavior?

CC learning should work as expected in old songs too, shouldn’t it? Without having to re-save song first

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

Nightly-B6AECCA

**Comment by Icoustic** [comment]
Actually scratch the “works as expected part” - *some* audio clips and synths work and others don’t, I can’t see an obvious difference that would be a reasonable reason. Pretty strange. I’ll link the song xml soon

**Comment by m-m-adams** [comment]
The official firmware has a significant number of midi handling bugs that lead incoming normal midi to be incorrectly treated as MPE zones and vice versa. Most likely what you're encountering is midi that was incorrectly learnt to the wrong channel and is now being correctly interpreted as not matching.

Once you share a broken song xml I'll be able to confirm

**Comment by m-m-adams** [comment]
Closing for now - please reopen if you can provide a problem XML

**Comment by Icoustic** [comment]
> Closing for now - please reopen if you can provide a problem XML

Yeah I will, just forgot to save with new CC learns and bring before leaving studio area where Deluge is currently staying

**Comment by Icoustic** [comment]
> Closing for now - please reopen if you can provide a problem XML

Aha! I found the answer, it wasn’t that. I was learning to and moving CCs in clip clones that were muted and not the last one to play, and the CC only (correctly) moves in the clip clone that was last unmuted.
I didn’t know that! Nice 👍
