### ISSUE TITLE
Reduce Parameter storage size

### ISSUE THREAD

**Issue by PaulFreund** [SynthstromAudible/DelugeFirmware#644]
Currently every instrument (including every drum row) has a full set of all parameters in memory even if they are not changed from default values and not automated. It might make sense to use a Resizable array for that and start rendering from an empty template and copying only changed/automated params into it / apply default values otherwise. For an 8 sample drum kit every clip takes about 60k of param memory which severely limits how many clips can be created without loosing performance by swapping into external SDRAM.

**Comment by m-m-adams** [comment]
My gut feel is that storing a baseline value per kit-clip instance would be of minimal value (I suspect most parameters are different in each row), but storing a baseline set per sound/instrument and then only storing changes in each clip would be huge

It'd also neatly solve the problem of editing your main clip and updating all the other instances, if you'd never changed the others from the baseline they'd just get the new values automatically
