### ISSUE TITLE
LED brightness setting lost after reboot

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#659]
### Please describe the problem:

Every time you boot, the setting for the brightness of the LEDs is lost. 

### What is the expected behavior?

Actually it is default. But its really annoying to do this every time.

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly

### If possible provide the steps to reproduce the issue and upload additional media:

- set brightness
- Reboot
- Brightness setting is lost

**Comment by bobtwinkles** [comment]
Fixed by #788 when that lands
