### ISSUE TITLE
MIDI CC parameter jumps to maximum value when turning gold knob

### ISSUE THREAD

**Issue by sdesign75** [SynthstromAudible/DelugeFirmware#670]
### Please describe the problem:

Cannot use gold encoders to control MIDI CC’s. After assigning a midi CC to a gold knob, when you turn the knob it jumps to the maximum value and cannot be changed.

### What is the expected behavior?

Gold knob changes the midi cc parameter

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

1.0.0-BETA-A258921

**Comment by sdesign75** [comment]
Can anyone confirm this bug?

**Comment by m-m-adams** [comment]
fixed by #678

**Comment by sdesign75** [comment]
Awesome!
