### ISSUE TITLE
Sync-Scaling not functional

### ISSUE THREAD

**Issue by sdesign75** [SynthstromAudible/DelugeFirmware#673]
### Please describe the problem:

Button does nothing when pressed

### What is the expected behavior?

It should enable sync scaling

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

1.0.0-BETA-A258921

**Comment by m-m-adams** [comment]
Go to community features and change the sync scaling option. More info can be found here: https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/community_features.md#434---fill-mode

**Comment by sdesign75** [comment]
Thanks, I didn’t realise it had been overridden :-)
