### ISSUE TITLE
deluge community build A77E2DE hard crash in settings menu

### ISSUE THREAD

**Issue by duncanrmi** [SynthstromAudible/DelugeFirmware#685]
### Please describe the problem:

in the settings menu, attempting to select either 'sticky shift' or 'light shift' crashes the unit.

machine is OLED, build is deluge-v1_0_0-beta+2023_11_05-a77e2de

### What is the expected behavior?

sticky shift/illuminated shift button

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

deluge-v1_0_0-beta+2023_11_05-a77e2de

### If possible provide the steps to reproduce the issue and upload additional media:

turned on, entered settings menu/community build, scrolled down to either of the shift key options, attempted to alter settings.

after a few seconds, a pattern appears in the grid [pic].
![crashed deluge](https://github.com/SynthstromAudible/DelugeFirmware/assets/149965194/81567687-13d7-4140-9d66-e49e3205c03d)

**Comment by alifeinbinary** [comment]
Noticing this issue as well with firmware 1.0.0-beta-5A9C21D. The Deluge also locks up if you try to scroll past LIGHT SHIFT. @m-m-adams suspects it might be related to the type of encoder, so I'll add that my unit is a retrofitted 7SEG era model from 2018. When did you buy yours @duncanrmi ?

**Comment by m-m-adams** [comment]
Fine until https://github.com/SynthstromAudible/DelugeFirmware/commit/390630a47bb2de655a1ac37a3137d5cbbb145545

**Comment by duncanrmi** [comment]
april 2018, is my original unit; the unit affected is my second one though, with a slightly later s/n. (bought used)
still 2018 I’d say.
both OLED.

On 7 Nov 2023, at 00:47, Andrew Halliwell ***@***.***> wrote:


Noticing this issue as well with firmware 1.0.0-beta-5A9C21D. The Deluge also locks up if you try to scroll past LIGHT SHIFT. @m-m-adams <https://github.com/m-m-adams> suspects it might be related to the type of encoder, so I'll add that my unit is a retrofitted 7SEG era model from 2018. When did you buy yours @duncanrmi <https://github.com/duncanrmi> ?

**Comment by duncanrmi** [comment]
180421 & 180505; this latter has the issue. both (presumably) 2018 machines- is that the date in the s/n?

**Comment by m-m-adams** [comment]
Fixed by #694
