### ISSUE TITLE
Scroll bar skips every other column on new songs

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#729]
### Please describe the problem:

The scroll bar in a kit or synth / audio clip skips every other column. Happens only in melt created songs. Older saved songs work as expected.

### What is the expected behavior?

Scroll with showing up on every column.

### Is there a relevant Pull request?

Ni

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly, community

### If possible provide the steps to reproduce the issue and upload additional media:

Create new song

go into a clip

press play

https://github.com/SynthstromAudible/DelugeFirmware/assets/62035517/33bc0df7-d2a6-496d-aa93-b880b58dfd6c

**Comment by m-m-adams** [comment]
Can't reproduce - from discord troubleshooting it may have been a power issue
