### ISSUE TITLE
Master Compressor issues

### ISSUE THREAD

**Issue by DelayDude** [SynthstromAudible/DelugeFirmware#736]
### Please describe the problem:

I´ve installed the latest beta (1.0.0 beta 202_11_17) on my OLED deluge and the master compressor has some issues. I can´t switch to attack and decay anymore, the LEDs don´t show the ammount of compression anymore and it crackles, when I turn the knobs. 

### What is the expected behavior?

No crackle
switch between attack decay threshold ...
LEDs show compression

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

1.0.0 beta

**Comment by m-m-adams** [comment]
The interface has changed - see here: https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/community_features.md#411---master-compressor

In one knob mode there is no metering. When in full editing mode (enter by pressing sidechain knob) the meter appears and you switch between parameters on the bottom knob. The interface is essentially the same as modfx and filters
