### ISSUE TITLE
Lag when changing wav files directory

### ISSUE THREAD

**Issue by rpc9943** [SynthstromAudible/DelugeFirmware#740]
### Please describe the problem:

In a large drum loops folder its visually lagging as i scroll. All wavs are correct , issue used to be in a beta with rohan and he fixed it but looks like its back?

### What is the expected behavior?

To not visually lag

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.0.0 betaD5331ED

### If possible provide the steps to reproduce the issue and upload additional media:

In a large drum loops folder its visually lagging as i scroll. All wavs are correct format, issue used to be in a beta with rohan and he fixed it but looks like its back?

**Comment by sichtbeton** [comment]
Can’t replicate. Is this still true at your end?
