### ISSUE TITLE
Solo function not present in grid mode

### ISSUE THREAD

**Issue by rpc9943** [SynthstromAudible/DelugeFirmware#741]
### Please describe the problem:

Solo is not working on grid mode. Works on rows.

### What is the expected behavior?

For grid to be able to use solo function as it works in rows

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.0.0 betaD5331ED

### If possible provide the steps to reproduce the issue and upload additional media:

Hold leftright knob down press the clip on grid mode. It does not solo. It works this way in rows view where you press the mute launch pad.

**Comment by m-m-adams** [comment]
Honestly didn't know that shortcut existed

**Comment by PaulFreund** [comment]
This is a bug if select in green mode setting is active, need to fix it
