### ISSUE TITLE
Need to be able to set source of audio clip from grid view

### ISSUE THREAD

**Issue by rpc9943** [SynthstromAudible/DelugeFirmware#742]
### Please describe the problem:

I can record to a blank audio clip which is great but i cant set the source of it like i can in rows view, which is hold learn and press the row pad. Will need to have a way to set source of audio clip from grid somehow

### What is the expected behavior?

To be able to change source of blank audio clip from grid mode

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.0.0 betaD5331ED

### If possible provide the steps to reproduce the issue and upload additional media:

From rows view create an audio clip , learn and row pad shows source of audio. We have no means of doing this from grid mode, maybe we can add source from the menu in the clip view?

**Comment by PaulFreund** [comment]
This works in blue mode same combination as rows
