### ISSUE TITLE
Zoom status message (ex. 16th notes) stuck in grid mode on oled

### ISSUE THREAD

**Issue by rpc9943** [SynthstromAudible/DelugeFirmware#743]
### Please describe the problem:

Popup Message in rectangle on oled screen sticks.
Hold leftright mnob down, press grid pad.
Message example "16th notes" stays on screen.
Fixed by pressing leftright knob again,

### What is the expected behavior?

Not sure why its even showing the zoom from grid view, but if it shows it, shouldnt stay on screen until i press the knob again

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.0.0 betaD5331ED

### If possible provide the steps to reproduce the issue and upload additional media:

1. Grid mode
2. Hold leftright knob down and press a grid pad
3. message stays on screen

**Comment by PaulFreund** [comment]
Basically same bug as #741, will be fixed
