### ISSUE TITLE
Automatic folders visible

### ISSUE THREAD

**Issue by sichtbeton** [SynthstromAudible/DelugeFirmware#76]
There is something wrong with the 4.14 alpha 3 and saving / folder viewing on a 7seg. Instead of hiding the automatically created sample folders it shows them. This was a feature that seemingly never made it into the open source version. In the official release of the fw it’s correct.

**Comment by bobtwinkles** [comment]
@dctucker was poking around in this code, maybe he has some insight in to why this could be happening?

**Comment by dctucker** [comment]
I can observed that the `Browser` (which deals with load/save in general) behaves differently, and the user experience immediately becomes unstable with the slightest code-change to `CStringArray`. I haven't had a chance to debug it yet.
🔜
