### ISSUE TITLE
Kit with random number of sounds gets created when switching clip type from Audio to Kit

### ISSUE THREAD

**Issue by laikrodiz** [SynthstromAudible/DelugeFirmware#760]
### Please describe the problem:

Kit with random number of sounds gets created when switching clip type from Audio to Kit.
Every time you repeat this, say convert Kit back to Audio, then back to Kit, the number of sounds in a Kit changes.

### What is the expected behavior?

Full kit should be loaded when switching clip type from Audio clip to Kit clip.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

community

### What is the firmware name:

deluge-v1_0_0-beta+2023_11_23-4c959c6.bin

### If possible provide the steps to reproduce the issue and upload additional media:

Steps to reproduce:

1. Create new track, switch to Song mode
2. Create an empty audio clip
3. Hold the clip pad and press Kit. Audio clip is converted to Kit clip.
4. Enter the Kit clip to see, that it has random number of sounds loaded.

**Comment by seangoodvibes** [comment]
Should fixed with PR #1532
