### ISSUE TITLE
Gold knob value pop up is on the wrong side on 7seg

### ISSUE THREAD

**Issue by m-m-adams** [SynthstromAudible/DelugeFirmware#761]
### Please describe the problem:

Pop up should be in right two digits, instead it’s appearing in the left two. Currently this causes flickering as menus and note popups render in the right digits

### What is the expected behavior?

Right digits to match menus and not conflict with note pop up.

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Built from release/1.0

**Comment by PaulFreund** [comment]
Is this something for future release of do you want to fix during RC?

**Comment by m-m-adams** [comment]
It'll depend how easy the fix is - I haven't looked at it at all yet

Maybe @seangoodvibes knows?
