### ISSUE TITLE
Delay trails missing

### ISSUE THREAD

**Issue by Icoustic** [SynthstromAudible/DelugeFirmware#771]
### Please describe the problem:

Delay trails after muting clips with delay on are missing from audio clips and affect entire kit clips.
(They’re present in those situations in official firmware)

### What is the expected behavior?

Delay trails should be present

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### If possible provide the steps to reproduce the issue and upload additional media:

Put delay on audio clip, shift+mute clip while playing - delay repeats cut off
(Conversely, do the same with a synth clip and the trails carry on after mutes)

And, put affect entire delay on kit clip, mute while playing, delay repeats cut off.

**Comment by PaulFreund** [comment]
Confirmed, we're working on a fix :)

**Comment by PaulFreund** [comment]
This is fixed in RC :)
