### ISSUE TITLE
drum kit - load random sample causes crashes / freezes the deluge

### ISSUE THREAD

**Issue by DelayDude** [SynthstromAudible/DelugeFirmware#786]
### Please describe the problem:

I´ve loaded the first factory kit and randomized the kick and snare. That works great but as soon as I´ve randomized the hat, the deluge freezes. I have to push the select button, to recover it. 

### What is the expected behavior?

no crashes when randomizing the third sample sound  :-)

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

community

### What is the firmware name:

1.0.0 Amadeus

### If possible provide the steps to reproduce the issue and upload additional media:

1. randomize kick in a drum kit
2. randomize snare in a drum kit
3. randomize hats (deluge crashes)

**Comment by DelayDude** [comment]
Edit: only happend once.

**Comment by m-m-adams** [comment]
Do you remember what the freeze message was?

**Comment by DelayDude** [comment]
I don´t remember the error code number . But the display said something like: "press select to attempt resume. Then save to a new file."

**Comment by scnroy** [comment]
Not sure if this is the same issue, but I can reliably get the Deluge to crash (random LEDs light up and bzzzzzzzzzz sound—no error message on OLED) if i do randomize drum on a kit using synth drum sounds (in my case the Drummage pack). 

Happy to open another issue if it'd be easier to track that way.

**Comment by m-m-adams** [comment]
I think that sounds different - could you open another one?
