### ISSUE TITLE
Scrolling through presets gets laggy (CPU?) when 8 initalized synth clips are created

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#787]
### Please describe the problem:

creating 8 new unique synth clips, then initializing each of them will create a CPU slow down. this is visible when choosing one synth clip to scroll presets with via SELECT and noticing lag. can occur with as little as 4 init clips.

notes:
on 7SEG: initialized presets all have the name '0' and do not increment (separate but related issue?)
on OLED: initialized presets all have the name 'SYNTH#', increment, but i believe is different from official where it should be 'SYNTH###' (not confirmed).

### What is the expected behavior?

confirmed with v4.1.4-RC, no slow down/lag should occur when scrolling quickly (quickly flicking SELECT) through presets while in Song view should occur with 8 init synth clips present.

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Built from release/1.0

### What is the firmware name:

c1.0.0

**Comment by caseygipson** [comment]
I'm just now noticing laggy synth scrolling on a new project with 5 newly initialized wavetable synths and 1 newly initialized kit instrument. The problem does not go away after a reboot and settings > firmeware > Y, available memory looks the same on initial load as a brand new project.

**Comment by m-m-adams** [comment]
I believe this comes from the fix for #715 and #718 requiring extra sd reads 

Hopefully I can come up with a better fix going forward

**Comment by dzaxy** [comment]
synth kit preset wavetable scroling is cryptonite for my oled deluge too

**Comment by SimonSaysBoo** [comment]
Yes, I've got laggy synth preset scrolling on a fresh song with nothing entered

**Comment by sichtbeton** [comment]
Is this still the case? At least here not anymore in latest nightly. Could be closed?

**Comment by seangoodvibes** [comment]
> Is this still the case? At least here not anymore in latest nightly. Could be closed?

Yea it is still the case.

If you create a synth clip with an arp and set a rhythm param value it's pretty noticeable.

**Comment by m-m-adams** [comment]
That's definitely a different problem. This issue arises when you have multiple presets in your song that don't exist on the sd card, and comes from unnecessarily checking to see if they exist on the card
