### ISSUE TITLE
Grid view does not display all clips

### ISSUE THREAD

**Issue by gobcmmelo** [SynthstromAudible/DelugeFirmware#798]
### Please describe the problem:

Clips in rows view that share the same instrument and are in the same section display as a single pad in grid view. This allows view/edit to only one version of the clip from grid view. In grid view clips can be alternately played by selecting the corresponding mute/launch pad.

### What is the expected behavior?

Grid view displays all clips and multiple clips that use the same instrument are displayed in a single column even if they are in the same section.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from release/1.0

### What is the firmware name:

C1.0.0

### If possible provide the steps to reproduce the issue and upload additional media:

Created a song with a multiple clips using the same instrument that are in the same section. Switch to grid view.

**Comment by ok-reza** [comment]
I believe this is a result of the two same-instrument clips sharing the same section color. Although Rows View allows for that, it's not exactly clear in Grid View how that would be handled in a way that is clear/makes sense. This is a currently known limitation unless you are describing something different.

**Comment by gobcmmelo** [comment]
> I believe this is a result of the two same-instrument clips sharing the same section color. Although Rows View allows for that, it's not exactly clear in Grid View how that would be handled in a way that is clear/makes sense. This is a currently known limitation unless you are describing something different.

That appears to be it. Thanks, I guess this would be categorized as an enhancement then. Thanks!

**Comment by m-m-adams** [comment]
Closing the issue, but feel free to open a discussion if you have ideas for how to display the different variants in grid view!

**Comment by gobcmmelo** [comment]
Totally makes sense, thanks!

> Closing the issue, but feel free to open a discussion if you have ideas for how to display the different variants in grid view!
