### ISSUE TITLE
Creating an audio clip in arranger view then adjusting the clip causes a crash (E369 error)

### ISSUE THREAD

**Issue by baymud** [SynthstromAudible/DelugeFirmware#832]
### Please describe the problem:

If you create an audio clip in arranger view then hold the audition pad of that lane and attempt to adjust the gold volume knob the Deluge crashes, displaying E369. 

This does not seem to happen if you create the audio clip in song view first (or just do the same adjustment in song view). 

### What is the expected behavior?

You should be able to adjust the volume of the audio clip lane in arranger view without a crash occurring. 

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.0/Amadeus

### What is the firmware name:

C.1.0.0

### If possible provide the steps to reproduce the issue and upload additional media:

- Create an audio clip in arranger view
- Hold the audition pad of that audio lane and adjust the volume knob
- Crash

![deluge-audio-error](https://github.com/SynthstromAudible/DelugeFirmware/assets/138159441/87b8b0a5-0617-4a64-bfa1-08a48603b3f9)

**Comment by bobtwinkles** [comment]
This is fixed by 073d023f27c94c84245db4b3195fdf34a93ea77f.

**Comment by bobtwinkles** [comment]
Specifically we likely just need the drive-by fix (d2a4147448774a3f5d607bc03c72c33ab130e2e5)

**Comment by bobtwinkles** [comment]
Fixed in 1.0.1 RC by https://github.com/SynthstromAudible/DelugeFirmware/issues/832
