### ISSUE TITLE
MIDI learned controls can be corrupted due to invalid offsets in flash storage

### ISSUE THREAD

**Issue by bobtwinkles** [SynthstromAudible/DelugeFirmware#839]
### Please describe the problem:

The offsets for flash are overlapping, so midi learned controls corrupt eachother

### What is the expected behavior?

MIDI learned controls should not corrupt eachother

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Release 1.0/Amadeus

**Comment by 0beron** [comment]
Fix to address this now in:
https://github.com/SynthstromAudible/DelugeFirmware/pull/843

**Comment by bobtwinkles** [comment]
Fixed by #843.
