### ISSUE TITLE
Waveform Loop Lock should have a visual indication that the loop is currently locked

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#845]
Rather than just relying on the popups, we should draw the pad grid differently somehow. Bikeshed proposal: Render the upper and lower halves of the loop indicators with different colors (cyan/magenta on the top/bottom of the start, and magenta/cyan on the top/bottom of the end maybe?)

**Comment by ok-reza** [comment]
a cool idea visually, i think it would work well with only loop points but i think it would be confusing with the following consideration:

i totally think start/end point locking should be a thing also (length lock?). if your visual suggestion was implemented for both loop and length lock, i think it would get confusing to see half of, say, the column red at the start point. once you are zoomed in and can't see the context of both points, you may mistake it for the other point.

here are some rough mock ups of options:

1)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/13c946d9-3ba5-41cb-af9c-8e0dbaefa48e)
your bikeshed proposal (maybe the bottom half colors should only be 3 rows to emphasize what the column represents (5 green and 3 red = start point)

2)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/aa2cec33-79df-40cb-9a1d-70113b2b9d62)
when locked, the two columns share the same color (in this case, the color inbetween the two in an additive color space)

3)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/b32d3e9a-f567-4c8a-b721-021a0732d344)
same concept as above but alternating

4)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/be91a111-8821-48b1-93df-5a0157d582af)
same concept but with only tops and bottoms changed (makes main color more distinct)

5)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/df564b96-e126-4c11-8e37-2ed0b1660015)
counter part's colors only on bottom to keep things clear if reading from top to bottom

6)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/149f3877-e7f0-4729-8f33-2e4ea41e5d3a)
same concept as above but with yellow/blue

7)![image](https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/34fdbada-8f16-4964-8fcc-92fe5caaccae)
alternating colors but only one color. yellow = locked. would need a special case when eg. green and cyan meet, yellow is ignored so green and cyan alternate.

after making the mock ups, i think 7 feels the best and is clearest.

**Comment by M0R172** [comment]
I would prefer 6 or 2, the others look too busy to me, especially the alternating colors of 3 and 7.

The calm and clear look of 2 makes me wonder if the pairs should maybe *always* be the same color, and the do an additional marker as in 6 when they are locked together?

**Comment by ok-reza** [comment]
good feedback!

the issue with matching pairs (eg. start and end, loop start/loop end) is that when zoomed in, you can't visually discern if the column represents the start or the end, we don't want users to think they're editing an end point but are actually editing the start point.

another option just occurred to me, something like 7 but no color (yellow) inbetween. just dotted cyan/magenta or dotted red/green

**Comment by M0R172** [comment]
But now that I think of it - since selecting one when they are locked together is equivalent to "selecting both", the blinking would make a LOT of sense! 

OK, and then, how about additionaly indicating locking, to be visible when only one marker is on screen. by extending the "foot", i.e. the bottom of the marker, one or two pads towards the partner, like this:

![deluge1](https://github.com/SynthstromAudible/DelugeFirmware/assets/155909144/fe3e8eca-8e6a-4927-a28f-779156dd387c)
