### ISSUE TITLE
When loop lock is engaged, the loop can not be moved towards the other endpoint if the endpoints are adjacent

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#846]
### Please describe the problem:

If a loop is locked and the start/end of the loop are adjacent, trying to move the loop start right or the loop end left fails because it would create overlap.

### What is the expected behavior?

The start/end should be shifted together in such a way as to allow scrolling through the whole sample.

### Is there a relevant Pull request?

293

### What hardware did you reproduce it with?

OLED, 7SEG

### What firmware did you reproduce it with?

Release 1.0/Amadeus

**Comment by ok-reza** [comment]
+1 ! i guess the current solution is to zoom in once, but it would feel really nice to move both ways in the case described.
