### ISSUE TITLE
Waveform loop lock (and loop length) should be remembered between loop endpoints being taken in and out of the loop

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#847]
After #844, loop lock state is forgotten when loop points are removed. Instead, that state should be retained and restored when the loop points are present again. Important considerations:
  - What do we do when the user attempts to put the loop point in a location that would make the loop (as previously locked) exceed the sample bounds?
  - How do we display the fact that the loop is currently locked when none of the loop points are present? Is this even important?

**Comment by ok-reza** [comment]
hmm i don't think it's necessary to keep lock state once a loop point has been deleted, i think that would confuse the user (and creates more cases to worry about code wise)
