### ISSUE TITLE
Add a default setting for slices generated by kit slice load

### ISSUE THREAD

**Issue by sapphire-arches** [SynthstromAudible/DelugeFirmware#849]
Kits can be generated from samples by holding select when selecting the initial kit sample and scrolling to "SLICE". These slices currently generate kits where every sample is in "CUT" mode. However, multiple users have requested the ability to default to "ONCE." We should add a default to the system defaults menu which allows setting this mode to one of the existing slice modes (ONCE/CUT/LOOP/STRETCH).

**Comment by trappar** [comment]
Also see: https://github.com/SynthstromAudible/DelugeFirmware/issues/510

**Comment by joxihan** [comment]
i was looking at this issue but it seems like it's not cut mode by default but more :
firstDrum->sources[0].repeatMode = (lengthMSPerSlice < 2002) ? SampleRepeatMode::ONCE : SampleRepeatMode::CUT;
So it's a question of lengthperslice.
Does it mean that we want to change the logic to replace by whatever is set as default slice repeat mode from the UI ?

**Comment by m-m-adams** [comment]
Yeah I think so - I think this logic is to try and guess whether it's a drum or a loop?

**Comment by sichtbeton** [comment]
Yep, this logic assumes stuff that’s not apparent. Maybe could there could be a toggle to preserve it?
