### ISSUE TITLE
Arpeggiator should not be an option of the Kit/Affect Entire FX menu

### ISSUE THREAD

**Issue by soymonitus** [SynthstromAudible/DelugeFirmware#875]
### Please describe the problem:

There is an option to change Arp settings from the new added Affect-Entire-Kit menu. When changing mode Deluge freezes. Besides, why arp settings for affect entire? Shouldn't the menu be completely removed? Also, maybe even Stutter should not be there as an option because it is available through the knobs

### What is the expected behavior?

There is no arpegiator menu in Affect Entire Kit menu

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

**Comment by soymonitus** [comment]
@seangoodvibes You developed this menu I think so asking you if there is a reason to have arp settings available

**Comment by seangoodvibes** [comment]
> @seangoodvibes You developed this menu I think so asking you if there is a reason to have arp settings available

I added it because Arp Gate is available as a Kit Affect Entire param, but I'm not sure if it does anything. If it doesn't it can be removed.

Probably same for stutter rate.

**Comment by soymonitus** [comment]
Why would arp gate affect a bunch of kit rows which could even not have arp ON? It doesn't make much sense to me, even if it works somehow because the code paths allow it, it is not intuitive at all and should be removed
