### ISSUE TITLE
Missing USB MIDI devices

### ISSUE THREAD

**Issue by drbourbon** [SynthstromAudible/DelugeFirmware#90]
Just build from origin/community and noticed that external MIDI devices connected via USB are not visible under Settings -> MIDI -> Devices.

They are visible with last official 7-segments Synthstrom firmware V4p0p1 and with firmware released by @alter-alter in his fork here: https://github.com/alter-alter/DelugeFirmware/releases/tag/1.0.5_randomizer

Steps to reproduce (darwin, macOS 12.6.5):
`git clone https://github.com/SynthstromAudible/DelugeFirmware && cd DelugeFirmware && ./dbt dbt-build-debug-7seg`

**Comment by m-m-adams** [comment]
I'll troubleshoot later today - I suspect the hosted usb midi device structure isn't getting properly initialized with the change to have an array of virtual ports per device

**Comment by m-m-adams** [comment]
@drbourbon to help me narrow it down could you confirm if the problem is just that the hosted devices can't be seen in the menu, or are they also not sending/receiving midi?

**Comment by drbourbon** [comment]
> @drbourbon to help me narrow it down could you confirm if the problem is just that the hosted devices can't be seen in the menu, or are they also not sending/receiving midi?

I just tried and I can't send nor receive midi (tried with a standard MIDI device and with a MPE device)

**Comment by m-m-adams** [comment]
> > @drbourbon to help me narrow it down could you confirm if the problem is just that the hosted devices can't be seen in the menu, or are they also not sending/receiving midi?
> 
> 
> 
> I just tried and I can't send nor receive midi (tried with a standard MIDI device and with a MPE device)

Could you try building from the PR to fix this? I believe I've got it working now, no issues hosting my linnstrument

**Comment by drbourbon** [comment]
It's working now, thanks
