### ISSUE TITLE
Kit/alphanumeric Order Inconsistencies

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#97]
This is part of the pre-OLED to post-OLED firmware inconsistencies I've noticed after loading the open-source community  firmware onto a 7-SEG display Deluge. (See #76, #98, #99, #100, #101)

### Kit/alphanumeric order inconsistencies and crashes.

Video showing the problem: https://www.youtube.com/watch?v=iq0kG6glywE

- The alphanumeric ordering seems to be changed

1. Expected: A1, A2, A3, B1, B2, B3, C1, etc.
2. Observed: A1, B1, C1, loops through a shortened list of kits, A2, B2, C2...inconsistent and unpredictable.

- A crash can occur when messing with the improper order found in the community firmware.

1. Certain kits aren't showing up at all, but can be revealed when scrolling backwards then forwards.
2. Doing so enough times causes a crash.

### Replicable on OLED?

It would be helpful to know if this issue persists on an OLED Deluge. I would suggest adding kits A1, A2, A3 through H1, H2, H3 yourself and sharing the behavior.

**Comment by litui** [comment]
Thanks for the push @rohanhill!  Slight slap on the wrist due for not using a Pull Request 😉, but I appreciate your attention to these issues. 🙇‍♀️
