### ISSUE TITLE
MIDI recording from arranger doesn't get note length

### ISSUE THREAD

**Issue by colinmeyer** [SynthstromAudible/DelugeFirmware#978]
### Please describe the problem:

1. New song
2. Midi clip
3. Arranger mode
4. Make sure midi track is armed for recording
5. Record, then play, press some buttons on external controller, to get some midi notes recorded to a newly minted fresh white clip (i.e. let the record function create the white clip, don't create it ahead)
6. Stop, enter newly created white clip. Observe that notes (at least after the first note) have the minimum lenth, instead of the proper length that the button was pressed

### What is the expected behavior?

All notes should record their proper length, when being written into a new white midi clip

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

a5a6fd056df41ef7f713e5642e5b338ae3b0f5dc

### If possible provide the steps to reproduce the issue and upload additional media:

see above

**Comment by Radius9999** [comment]
I discovered this does not happen if quantization is set to none.

**Comment by m-m-adams** [comment]
This is a quantization bug - the menu allowed setting impossible values which caused issues in some scenarios

**Comment by Radius9999** [comment]
#1348 did not fix the issue [Deluge Beta Release 20240229]
