### ISSUE TITLE
Waveform loop lock will go out of bounds and cause a crash.

### ISSUE THREAD

**Issue by ok-reza** [SynthstromAudible/DelugeFirmware#982]
### Please describe the problem:

Loop lock engaged and then adjusting loop end (magenta) will allow you to move left until the loop start (cyan) moves out of bounds beyond the start point (green). a crash then occurs.

E438

### What is the expected behavior?

moving loop end point (magenta) via SELECT turn (or pressing grid columns) should stop once loop start point (cyan) reaches 1 column before the start point (green). this behaves properly when controlling the start point (cyan) in relationship to the end point.

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Release 1.0/Amadeus, Nightly

### If possible provide the steps to reproduce the issue and upload additional media:

1) switch to kit clip
2) select any row and enter waveform view
3) create loop start and loop end point
4) enter loop lock (press and hold cyan then magenta)
5) select magenta so loop end point is active
6) turn SEL encoder counter clockwise or just select a column near start point; cyan will go left beyond the bounds and cause a crash.

**Comment by bobtwinkles** [comment]
Fixed by #983
